use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::path::PathBuf;

use traj_core::error::{TrajError, TrajResult};
use traj_core::frame::{Box3, FrameChunkBuilder};

use crate::TrajReader;

const NM_TO_ANGSTROM: f32 = 10.0;
const ANGSTROM_TO_NM: f32 = 0.1;
const BOX_TOL: f32 = 1.0e-6;

pub struct GroTrajReader {
    path: PathBuf,
    reader: BufReader<File>,
    n_atoms: usize,
    pending: Option<GroTrajFrame>,
}

pub struct GroTrajWriter {
    writer: BufWriter<File>,
    n_atoms: usize,
}

#[derive(Clone)]
struct GroTrajFrame {
    coords: Vec<[f32; 3]>,
    box_: Box3,
    time_ps: Option<f32>,
    velocities: Option<Vec<[f32; 3]>>,
}

impl GroTrajReader {
    pub fn open(path: impl Into<PathBuf>) -> TrajResult<Self> {
        let path = path.into();
        let file = File::open(&path)?;
        let mut reader = BufReader::new(file);
        let pending = parse_next_gro_frame(&mut reader)?;
        let Some(frame) = pending else {
            return Err(TrajError::Parse("no frames found in GRO trajectory".into()));
        };
        let n_atoms = frame.coords.len();
        if n_atoms == 0 {
            return Err(TrajError::Parse("no atoms found in GRO trajectory".into()));
        }
        Ok(Self {
            path,
            reader,
            n_atoms,
            pending: Some(frame),
        })
    }

    pub fn reset(&mut self) -> TrajResult<()> {
        let reopened = Self::open(self.path.clone())?;
        *self = reopened;
        Ok(())
    }
}

impl TrajReader for GroTrajReader {
    fn n_atoms(&self) -> usize {
        self.n_atoms
    }

    fn n_frames_hint(&self) -> Option<usize> {
        None
    }

    fn read_chunk(&mut self, max_frames: usize, out: &mut FrameChunkBuilder) -> TrajResult<usize> {
        let max_frames = max_frames.max(1);
        out.reset(self.n_atoms, max_frames);
        let mut frames = 0usize;
        while frames < max_frames {
            let frame = if let Some(frame) = self.pending.take() {
                Some(frame)
            } else {
                parse_next_gro_frame(&mut self.reader)?
            };
            let Some(frame) = frame else {
                break;
            };
            if frame.coords.len() != self.n_atoms {
                return Err(TrajError::Mismatch(format!(
                    "GRO frame atom count {} does not match first frame {}",
                    frame.coords.len(),
                    self.n_atoms
                )));
            }
            let box_ = if out.needs_box() {
                frame.box_
            } else {
                Box3::None
            };
            let time_ps = if out.needs_time() {
                frame.time_ps
            } else {
                None
            };
            let dst = out.start_frame(box_, time_ps);
            for (atom, src) in dst.iter_mut().zip(frame.coords.iter()) {
                atom[0] = src[0];
                atom[1] = src[1];
                atom[2] = src[2];
                atom[3] = 1.0;
            }
            let velocities = if out.needs_velocities() {
                frame.velocities.as_deref()
            } else {
                None
            };
            out.set_frame_extras(velocities, None, None)?;
            frames += 1;
        }
        Ok(frames)
    }
}

impl GroTrajWriter {
    pub fn create(path: impl Into<PathBuf>, n_atoms: usize) -> TrajResult<Self> {
        if n_atoms == 0 {
            return Err(TrajError::Invalid(
                "GRO trajectory writer requires at least one atom".into(),
            ));
        }
        let path = path.into();
        let file = File::create(path)?;
        Ok(Self {
            writer: BufWriter::new(file),
            n_atoms,
        })
    }

    pub fn write_frame(
        &mut self,
        coords: &[[f32; 3]],
        box_: Box3,
        step: usize,
        time_ps: Option<f32>,
        velocities: Option<&[[f32; 3]]>,
    ) -> TrajResult<()> {
        if coords.len() != self.n_atoms {
            return Err(TrajError::Mismatch(format!(
                "frame atom count {} does not match writer atom count {}",
                coords.len(),
                self.n_atoms
            )));
        }
        if let Some(velocities) = velocities {
            if velocities.len() != self.n_atoms {
                return Err(TrajError::Mismatch(format!(
                    "velocity atom count {} does not match writer atom count {}",
                    velocities.len(),
                    self.n_atoms
                )));
            }
        }

        writeln!(
            self.writer,
            "Generated by warp_md t={:10.5} step= {}",
            time_ps.unwrap_or(step as f32),
            step
        )?;
        writeln!(self.writer, "{:5}", self.n_atoms)?;
        for (idx, coord) in coords.iter().enumerate() {
            let atom_id = (idx + 1) % 100_000;
            let atom_name = truncate_atom_name(&format!("X{}", idx + 1));
            write!(
                self.writer,
                "{:>5}{:<5}{:>5}{:>5}{:>8.3}{:>8.3}{:>8.3}",
                1,
                "MOL",
                atom_name,
                atom_id,
                coord[0] * ANGSTROM_TO_NM,
                coord[1] * ANGSTROM_TO_NM,
                coord[2] * ANGSTROM_TO_NM
            )?;
            if let Some(velocities) = velocities {
                let velocity = velocities[idx];
                write!(
                    self.writer,
                    "{:>8.4}{:>8.4}{:>8.4}",
                    velocity[0] * ANGSTROM_TO_NM,
                    velocity[1] * ANGSTROM_TO_NM,
                    velocity[2] * ANGSTROM_TO_NM
                )?;
            }
            writeln!(self.writer)?;
        }
        writeln!(self.writer, "{}", gro_box_line(box_))?;
        Ok(())
    }

    pub fn flush(&mut self) -> TrajResult<()> {
        self.writer.flush()?;
        Ok(())
    }
}

fn parse_next_gro_frame<R: BufRead>(reader: &mut R) -> TrajResult<Option<GroTrajFrame>> {
    let title = loop {
        match read_optional_line(reader)? {
            Some(line) if !line.trim().is_empty() => break line,
            Some(_) => continue,
            None => return Ok(None),
        }
    };
    let atom_count_line = read_required_line(reader, "GRO atom count line")?;
    let n_atoms = atom_count_line.trim().parse::<usize>().map_err(|_| {
        TrajError::Parse(format!(
            "invalid GRO atom count '{}'",
            atom_count_line.trim()
        ))
    })?;
    let mut coords = Vec::with_capacity(n_atoms);
    let mut velocities: Option<Vec<[f32; 3]>> = None;
    for _ in 0..n_atoms {
        let line = read_required_line(reader, "GRO atom line")?;
        let (coord, velocity) = parse_gro_atom_line(&line)?;
        coords.push(coord);
        match (velocities.as_mut(), velocity) {
            (Some(values), Some(velocity)) => values.push(velocity),
            (Some(values), None) => values.push([0.0; 3]),
            (None, Some(velocity)) => {
                let mut values = vec![[0.0; 3]; coords.len() - 1];
                values.push(velocity);
                velocities = Some(values);
            }
            (None, None) => {}
        }
    }
    let box_line = read_required_line(reader, "GRO box line")?;
    Ok(Some(GroTrajFrame {
        coords,
        box_: parse_gro_box_line(&box_line)?,
        time_ps: parse_gro_time_ps(&title),
        velocities,
    }))
}

fn parse_gro_atom_line(line: &str) -> TrajResult<([f32; 3], Option<[f32; 3]>)> {
    let tail = line.get(20..).unwrap_or(line);
    let values = tail
        .split_whitespace()
        .map(|token| {
            token
                .parse::<f32>()
                .map_err(|_| TrajError::Parse(format!("invalid GRO numeric field '{token}'")))
        })
        .collect::<Result<Vec<_>, _>>()?;
    if values.len() < 3 {
        return Err(TrajError::Parse(format!("invalid GRO atom line: {line}")));
    }
    let coord = [
        values[0] * NM_TO_ANGSTROM,
        values[1] * NM_TO_ANGSTROM,
        values[2] * NM_TO_ANGSTROM,
    ];
    let velocity = if values.len() >= 6 {
        Some([
            values[3] * NM_TO_ANGSTROM,
            values[4] * NM_TO_ANGSTROM,
            values[5] * NM_TO_ANGSTROM,
        ])
    } else {
        None
    };
    Ok((coord, velocity))
}

fn parse_gro_box_line(line: &str) -> TrajResult<Box3> {
    let values = line
        .split_whitespace()
        .map(|token| {
            token
                .parse::<f32>()
                .map(|value| value * NM_TO_ANGSTROM)
                .map_err(|_| TrajError::Parse(format!("invalid GRO box value '{token}'")))
        })
        .collect::<Result<Vec<_>, _>>()?;
    match values.as_slice() {
        [] => Ok(Box3::None),
        [xx, yy, zz] => Ok(Box3::Orthorhombic {
            lx: *xx,
            ly: *yy,
            lz: *zz,
        }),
        [xx, yy, zz, xy, xz, yx, yz, zx, zy] => Ok(Box3::Triclinic {
            m: [*xx, *xy, *xz, *yx, *yy, *yz, *zx, *zy, *zz],
        }),
        _ => Err(TrajError::Parse(
            "GRO box line must contain 3 or 9 values".into(),
        )),
    }
}

fn gro_box_line(box_: Box3) -> String {
    match gro_box_fields(box_) {
        Some(fields) => fields
            .iter()
            .map(|value| format!("{value:>10.5}"))
            .collect::<Vec<_>>()
            .join(""),
        None => format!("{:>10.5}{:>10.5}{:>10.5}", 0.0, 0.0, 0.0),
    }
}

fn gro_box_fields(box_: Box3) -> Option<Vec<f32>> {
    match box_ {
        Box3::None => None,
        Box3::Orthorhombic { lx, ly, lz } => Some(vec![
            lx * ANGSTROM_TO_NM,
            ly * ANGSTROM_TO_NM,
            lz * ANGSTROM_TO_NM,
        ]),
        Box3::Triclinic { m } => {
            if is_orthorhombic(&m) {
                Some(vec![
                    m[0] * ANGSTROM_TO_NM,
                    m[4] * ANGSTROM_TO_NM,
                    m[8] * ANGSTROM_TO_NM,
                ])
            } else {
                Some(vec![
                    m[0] * ANGSTROM_TO_NM,
                    m[4] * ANGSTROM_TO_NM,
                    m[8] * ANGSTROM_TO_NM,
                    m[1] * ANGSTROM_TO_NM,
                    m[2] * ANGSTROM_TO_NM,
                    m[3] * ANGSTROM_TO_NM,
                    m[5] * ANGSTROM_TO_NM,
                    m[6] * ANGSTROM_TO_NM,
                    m[7] * ANGSTROM_TO_NM,
                ])
            }
        }
    }
}

fn is_orthorhombic(matrix: &[f32; 9]) -> bool {
    matrix[1].abs() <= BOX_TOL
        && matrix[2].abs() <= BOX_TOL
        && matrix[3].abs() <= BOX_TOL
        && matrix[5].abs() <= BOX_TOL
        && matrix[6].abs() <= BOX_TOL
        && matrix[7].abs() <= BOX_TOL
}

fn parse_gro_time_ps(title: &str) -> Option<f32> {
    let (_, tail) = title.split_once("t=")?;
    tail.trim_start()
        .split_whitespace()
        .next()
        .and_then(|value| value.parse::<f32>().ok())
}

fn read_optional_line<R: BufRead>(reader: &mut R) -> TrajResult<Option<String>> {
    let mut line = String::new();
    let read = reader.read_line(&mut line)?;
    if read == 0 {
        return Ok(None);
    }
    Ok(Some(line.trim_end_matches(['\r', '\n']).to_string()))
}

fn read_required_line<R: BufRead>(reader: &mut R, label: &str) -> TrajResult<String> {
    read_optional_line(reader)?
        .ok_or_else(|| TrajError::Parse(format!("truncated GRO frame while reading {label}")))
}

fn truncate_atom_name(value: &str) -> String {
    value.chars().take(5).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::xtc::XtcReader;
    use std::path::Path;

    fn fixture(name: &str) -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../python/warp_md/tests/fixtures/gro_g96")
            .join(name)
    }

    #[test]
    fn gro_reader_matches_xtc_fixture() {
        let mut gro = GroTrajReader::open(fixture("spc2-traj.gro")).unwrap();
        let mut xtc = XtcReader::open(fixture("spc2-traj.xtc")).unwrap();
        let mut gro_builder = FrameChunkBuilder::new(6, 4);
        gro_builder.set_requirements(true, true);
        gro_builder.set_optional_requirements(true, false, false);
        let mut xtc_builder = FrameChunkBuilder::new(6, 4);
        xtc_builder.set_requirements(true, true);
        let gro_read = gro.read_chunk(4, &mut gro_builder).unwrap();
        let xtc_read = xtc.read_chunk(4, &mut xtc_builder).unwrap();
        assert_eq!(gro_read, 2);
        assert_eq!(xtc_read, 2);
        let gro_chunk = gro_builder.finish().unwrap();
        let xtc_chunk = xtc_builder.finish().unwrap();
        assert_eq!(gro_chunk.coords.len(), xtc_chunk.coords.len());
        for (lhs, rhs) in gro_chunk.coords.iter().zip(xtc_chunk.coords.iter()) {
            assert!((lhs[0] - rhs[0]).abs() < 1.0e-4);
            assert!((lhs[1] - rhs[1]).abs() < 1.0e-4);
            assert!((lhs[2] - rhs[2]).abs() < 1.0e-4);
        }
        assert_eq!(gro_chunk.box_, xtc_chunk.box_);
        assert_eq!(gro_chunk.time_ps, xtc_chunk.time_ps);
        let velocities = gro_chunk.velocities.unwrap();
        assert_eq!(velocities.len(), 12);
        assert!((velocities[0][0] - 5.69).abs() < 1.0e-4);
        assert!((velocities[11][2] - 84.65).abs() < 1.0e-4);
    }

    #[test]
    fn gro_writer_roundtrips_frames() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("roundtrip.gro");
        let mut writer = GroTrajWriter::create(&path, 2).unwrap();
        writer
            .write_frame(
                &[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
                Box3::Orthorhombic {
                    lx: 20.0,
                    ly: 21.0,
                    lz: 22.0,
                },
                0,
                Some(0.25),
                Some(&[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]),
            )
            .unwrap();
        writer
            .write_frame(
                &[[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]],
                Box3::Triclinic {
                    m: [23.0, 1.0, 2.0, 3.0, 24.0, 4.0, 5.0, 6.0, 25.0],
                },
                1,
                Some(1.75),
                None,
            )
            .unwrap();
        writer.flush().unwrap();

        let mut reader = GroTrajReader::open(&path).unwrap();
        let mut builder = FrameChunkBuilder::new(2, 2);
        builder.set_requirements(true, true);
        builder.set_optional_requirements(true, false, false);
        assert_eq!(reader.read_chunk(2, &mut builder).unwrap(), 2);
        let chunk = builder.finish().unwrap();
        assert_eq!(chunk.n_frames, 2);
        assert!((chunk.coords[0][0] - 1.0).abs() < 1.0e-3);
        assert!((chunk.coords[3][2] - 12.0).abs() < 1.0e-3);
        assert_eq!(chunk.time_ps.unwrap(), vec![0.25, 1.75]);
        let velocities = chunk.velocities.unwrap();
        assert!((velocities[0][0] - 0.1).abs() < 1.0e-3);
        assert_eq!(velocities[2], [0.0, 0.0, 0.0]);
        assert_eq!(
            chunk.box_[1],
            Box3::Triclinic {
                m: [23.0, 1.0, 2.0, 3.0, 24.0, 4.0, 5.0, 6.0, 25.0],
            }
        );
    }
}
