root: ./docs

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  tutorial: tutorial/README.md
  reference: reference/README.md
  pack: guides/packing.md
  validation: guides/validation.md
