use super::*;

pub(super) fn lookup_solvent_library(name: &str) -> Option<SolventLibraryEntry> {
    if let Some(entry) = lookup_tailcode_solvent_library(name) {
        return Some(entry);
    }
    match normalize_library_name(name).as_str() {
        "W" => Some(SolventLibraryEntry {
            name: "W".to_string(),
            mapping_ratio: 4.0,
            molar_mass_g_mol: 18.01528,
            density_kg_m3: 996.69,
            beads: vec![solvent_library_bead("W", [0.0, 0.0, 0.0], 0.0)],
        }),
        "SW" => Some(SolventLibraryEntry {
            name: "SW".to_string(),
            mapping_ratio: 3.0,
            molar_mass_g_mol: 18.01528,
            density_kg_m3: 996.69,
            beads: vec![solvent_library_bead("SW", [0.0, 0.0, 0.0], 0.0)],
        }),
        "TW" => Some(SolventLibraryEntry {
            name: "TW".to_string(),
            mapping_ratio: 2.0,
            molar_mass_g_mol: 18.01528,
            density_kg_m3: 996.69,
            beads: vec![solvent_library_bead("TW", [0.0, 0.0, 0.0], 0.0)],
        }),
        "WF" => Some(SolventLibraryEntry {
            name: "WF".to_string(),
            mapping_ratio: 4.0,
            molar_mass_g_mol: 18.01528,
            density_kg_m3: 996.69,
            beads: vec![solvent_library_bead("WF", [0.0, 0.0, 0.0], 0.0)],
        }),
        "SOL" | "SOLTIP3" | "SOLTIP3P" | "TIP3SOL" | "TIP3PSOL" => {
            Some(atomistic_tip3_water_entry("SOL"))
        }
        "SOLTIP4" | "SOLTIP4P" | "TIP4SOL" | "TIP4PSOL" => Some(atomistic_tip4_water_entry("SOL")),
        "SOLTIP5" | "SOLTIP5P" | "TIP5SOL" | "TIP5PSOL" => Some(atomistic_tip5_water_entry("SOL")),
        "TIP3" | "TIP3P" => Some(atomistic_tip3_water_entry("TIP3")),
        "TIP4" | "TIP4P" => Some(atomistic_tip4_water_entry("TIP4")),
        "TIP5" | "TIP5P" => Some(atomistic_tip5_water_entry("TIP5")),
        "CHARMMTIP3" | "CHARMMTIP3P" => Some(SolventLibraryEntry {
            name: "TIP3".to_string(),
            mapping_ratio: 1.0,
            molar_mass_g_mol: 18.01528,
            density_kg_m3: 996.69,
            beads: vec![
                solvent_library_bead("OH2", [0.0, 0.0, 0.0], -0.834),
                solvent_library_bead("H1", [0.74, 0.64, 0.0], 0.417),
                solvent_library_bead("H2", [-0.74, 0.64, 0.0], 0.417),
            ],
        }),
        "TP3" | "AMBERTIP3" | "AMBERTIP3P" => Some(SolventLibraryEntry {
            name: "TP3".to_string(),
            mapping_ratio: 1.0,
            molar_mass_g_mol: 18.01528,
            density_kg_m3: 996.69,
            beads: vec![
                solvent_library_bead("O", [0.0, 0.0, 0.0], -0.834),
                solvent_library_bead("H1", [0.74, 0.64, 0.0], 0.417),
                solvent_library_bead("H2", [-0.74, 0.64, 0.0], 0.417),
            ],
        }),
        "OPC" => Some(SolventLibraryEntry {
            name: "OPC".to_string(),
            mapping_ratio: 1.0,
            molar_mass_g_mol: 18.01528,
            density_kg_m3: 996.69,
            beads: vec![
                solvent_library_bead("O", [0.0, 0.0, 0.0], 0.0),
                solvent_library_bead("H1", [0.54, 0.686, 0.0], 0.679142),
                solvent_library_bead("H2", [-0.54, 0.686, 0.0], 0.679142),
                solvent_library_bead("EPW", [0.0, 0.16, 0.0], -1.358284),
            ],
        }),
        "BENZ" => lookup_small_molecule_solvent_library("BENZ", 78.114, 876.5),
        "TOLU" => lookup_small_molecule_solvent_library("TOLU", 92.141, 866.9),
        "ENAPH" => lookup_small_molecule_solvent_library("ENAPH", 156.228, 992.0),
        "SUCR" | "SUCROSE" => lookup_small_molecule_solvent_library("SUCR", 342.30, 1587.0),
        "GLYL" => lookup_small_molecule_solvent_library("GLYL", 92.094, 1261.0),
        "PUT" => lookup_small_molecule_solvent_library("PUT", 88.15, 877.0),
        "SPER" => lookup_small_molecule_solvent_library("SPER", 145.25, 925.0),
        "UREA" => lookup_small_molecule_solvent_library("UREA", 60.056, 1320.0),
        "TREH" => lookup_small_molecule_solvent_library("TREH", 342.30, 1587.0),
        "C1" | "MIM" => lookup_small_molecule_solvent_library("C1", 97.14, 1000.0),
        "C2" | "EIM" => lookup_small_molecule_solvent_library("C2", 111.16, 1000.0),
        "C4" | "BIM" => lookup_small_molecule_solvent_library("C4", 139.22, 1000.0),
        "C8" | "OIM" => lookup_small_molecule_solvent_library("C8", 196.33, 1000.0),
        "C12" | "DIM" => lookup_small_molecule_solvent_library("C12", 252.44, 1000.0),
        "BF4" => lookup_small_molecule_solvent_library("BF4", 86.80, 1000.0),
        "DA" => lookup_small_molecule_solvent_library("DA", 331.22, 1000.0),
        "DC" => lookup_small_molecule_solvent_library("DC", 307.20, 1000.0),
        "DG" => lookup_small_molecule_solvent_library("DG", 347.22, 1000.0),
        "DT" => lookup_small_molecule_solvent_library("DT", 322.21, 1000.0),
        "ADEN" => lookup_small_molecule_solvent_library("ADEN", 135.13, 1000.0),
        "CYTO" => lookup_small_molecule_solvent_library("CYTO", 111.10, 1000.0),
        "GUAN" => lookup_small_molecule_solvent_library("GUAN", 151.13, 1000.0),
        "THYM" => lookup_small_molecule_solvent_library("THYM", 126.11, 1000.0),
        "URAC" => lookup_small_molecule_solvent_library("URAC", 112.09, 1000.0),
        "WT4" => lookup_small_molecule_solvent_library("WT4", 200.0, 996.69),
        other => lookup_standard_solvent_library(other)
            .or_else(|| lookup_amino_acid_solvent_library(other)),
    }
}
pub(super) fn known_solvent_library_names() -> Vec<&'static str> {
    let mut names = vec![
        "W",
        "SW",
        "TW",
        "WF",
        "SOL",
        "SOL-TIP3",
        "SOL-TIP4",
        "SOL-TIP5",
        "TIP3",
        "TIP4",
        "TIP5",
        "CHARMM-TIP3",
        "TP3",
        "OPC",
        "DMSO",
        "DMS",
        "ACN",
        "HEX",
        "OCT",
        "DOD",
        "HD",
        "HEXADECANE",
        "HXE",
        "HEXENE",
        "OCE",
        "OCTENE",
        "DOE",
        "DODECENE",
        "HXY",
        "HEXYNE",
        "OCY",
        "OCTYNE",
        "HXD14",
        "HEXADIENE",
        "OCD912",
        "OCTADECADIENE",
        "DCE",
        "DICHLOROETHANE",
        "CLF",
        "CHLOROFORM",
        "TCM",
        "TETRACHLOROMETHANE",
        "TCE",
        "TRICHLOROETHYLENE",
        "TFEOL",
        "TFE",
        "TRIFLUOROETHANOL",
        "MEO",
        "METHANOL",
        "ETO",
        "ETHANOL",
        "IPO",
        "ISOPROPANOL",
        "PRO",
        "PROPANOL",
        "BTO",
        "BUTANOL",
        "HXO",
        "HEXANOL",
        "HPO",
        "HEPTANOL",
        "OCO",
        "OCTANOL",
        "ETH",
        "DIETHYL-ETHER",
        "DISH",
        "DIISOPROPYL-ETHER",
        "DXE",
        "GLYME",
        "DIMETHOXYETHANE",
        "TXE",
        "TRIGLYME",
        "DISS",
        "DIISOPROPYL-SULFIDE",
        "PPN",
        "ACETONE",
        "BTN",
        "BUTANONE",
        "ANN",
        "ACETYLACETONE",
        "HXN",
        "HEXA-2-ONE",
        "HPN",
        "HEPTA-2-ONE",
        "BTA",
        "BUTANAL",
        "HXA",
        "HEXANAL",
        "HPA",
        "HEPTANAL",
        "MEA",
        "METHYL-ACETATE",
        "ETA",
        "ETHYL-ACETATE",
        "IBA",
        "ISO-BUTYL-ACETATE",
        "TBA",
        "T-BUTYL-ACETATE",
        "NBA",
        "N-BUTYL-ACETATE",
        "DEI",
        "DIETHYLAMINE",
        "TMI",
        "TRIMETHYLAMINE",
        "PPI",
        "PROPYLAMINE",
        "NDI",
        "DIMETHYLETHYLAMINE",
        "BTI",
        "BUTYLAMINE",
        "PTI",
        "PENTYLAMINE",
        "HXI",
        "HEXYLAMINE",
        "HPI",
        "HEPTYLAMINE",
        "OCI",
        "OCTYLAMINE",
        "ACAC",
        "ACETIC-ACID",
        "PRAC",
        "PROPANOIC-ACID",
        "DMFD",
        "DIMETHYLFORMAMIDE",
        "DMAD",
        "DIMETHYLACETAMIDE",
        "BENZ",
        "TOLU",
        "ENAPH",
        "SUCR",
        "SUCROSE",
        "GLYL",
        "PUT",
        "SPER",
        "UREA",
        "TREH",
        "C1",
        "C2",
        "C4",
        "C8",
        "C12",
        "BF4",
        "DA",
        "DC",
        "DG",
        "DT",
        "ADEN",
        "CYTO",
        "GUAN",
        "THYM",
        "URAC",
        "WT4",
        "hydrocarbon:<tailcode>",
        "fattyacid:<tailcode>",
        "monoglyceride:<tailcode>",
        "diglyceride:<tailcode>,<tailcode>",
        "triglyceride:<tailcode>,<tailcode>,<tailcode>",
        "bmp2:<tailcode>,<tailcode>",
        "bmp3:<tailcode>,<tailcode>",
        "cardiolipin:<tailcode>,<tailcode>,<tailcode>,<tailcode>",
        "sphingolipid:<head>,<tailcode>,<tailcode>",
    ];
    names.extend(known_ltf_named_tailcode_solvent_names());
    names.extend(known_amino_acid_solvent_names());
    names
}
