from pkgutil import extend_path

# Allow local source package + installed extension module to coexist.
__path__ = extend_path(__path__, __name__)

__version__ = "0.4.30"

_REQUIRED_BINDINGS = (
    ("System", "PySystem"),
    ("Selection", "PySelection"),
    ("Trajectory", "PyTrajectory"),
    ("TrajectoryWriter", "PyTrajectoryWriter"),
    ("StructureWriter", "PyStructureWriter"),
    ("FrameEditor", "PyFrameEditor"),
    ("RgPlan", "PyRgPlan"),
    ("RadgyrTensorPlan", "PyRadgyrTensorPlan"),
    ("RmsdPlan", "PyRmsdPlan"),
    ("SymmRmsdPlan", "PySymmRmsdPlan"),
    ("DistanceRmsdPlan", "PyDistanceRmsdPlan"),
    ("PairwiseRmsdPlan", "PyPairwiseRmsdPlan"),
    ("TrajectoryClusterPlan", "PyTrajectoryClusterPlan"),
    ("MatrixPlan", "PyMatrixPlan"),
    ("PcaPlan", "PyPcaPlan"),
    ("AnalyzeModesPlan", "PyAnalyzeModesPlan"),
    ("ProjectionPlan", "PyProjectionPlan"),
    ("RmsdPerResPlan", "PyRmsdPerResPlan"),
    ("RmsfPlan", "PyRmsfPlan"),
    ("BfactorsPlan", "PyBfactorsPlan"),
    ("AtomicAdpPlan", "PyAtomicAdpPlan"),
    ("AtomicFluctPlan", "PyAtomicFluctPlan"),
    ("DistancePlan", "PyDistancePlan"),
    ("LowestCurvePlan", "PyLowestCurvePlan"),
    ("VectorPlan", "PyVectorPlan"),
    ("GetVelocityPlan", "PyGetVelocityPlan"),
    ("SetVelocityPlan", "PySetVelocityPlan"),
    ("PairwiseDistancePlan", "PyPairwiseDistancePlan"),
    ("PairDistPlan", "PyPairDistPlan"),
    ("AnglePlan", "PyAnglePlan"),
    ("DihedralPlan", "PyDihedralPlan"),
    ("MultiDihedralPlan", "PyMultiDihedralPlan"),
    ("PermuteDihedralsPlan", "PyPermuteDihedralsPlan"),
    ("DihedralRmsPlan", "PyDihedralRmsPlan"),
    ("PuckerPlan", "PyPuckerPlan"),
    ("RotateDihedralPlan", "PyRotateDihedralPlan"),
    ("RotateDihedralTrajectoryPlan", "PyRotateDihedralTrajectoryPlan"),
    ("SetDihedralPlan", "PySetDihedralPlan"),
    ("SetDihedralTrajectoryPlan", "PySetDihedralTrajectoryPlan"),
    ("CheckChiralityPlan", "PyCheckChiralityPlan"),
    ("MindistPlan", "PyMindistPlan"),
    ("HausdorffPlan", "PyHausdorffPlan"),
    ("CheckStructurePlan", "PyCheckStructurePlan"),
    ("AtomMapPlan", "PyAtomMapPlan"),
    ("FixImageBondsPlan", "PyFixImageBondsPlan"),
    ("FixImageBondsTrajectoryPlan", "PyFixImageBondsTrajectoryPlan"),
    ("RandomizeIonsPlan", "PyRandomizeIonsPlan"),
    ("RandomizeIonsTrajectoryPlan", "PyRandomizeIonsTrajectoryPlan"),
    ("ClosestAtomPlan", "PyClosestAtomPlan"),
    ("SearchNeighborsPlan", "PySearchNeighborsPlan"),
    ("SearchNeighborListPlan", "PySearchNeighborListPlan"),
    ("WatershellPlan", "PyWatershellPlan"),
    ("ClosestPlan", "PyClosestPlan"),
    ("ClosestCoordsPlan", "PyClosestCoordsPlan"),
    ("NativeContactsPlan", "PyNativeContactsPlan"),
    ("CenterTrajectoryPlan", "PyCenterTrajectoryPlan"),
    ("CenterTrajectoryOutputPlan", "PyCenterTrajectoryOutputPlan"),
    ("TranslatePlan", "PyTranslatePlan"),
    ("TransformPlan", "PyTransformPlan"),
    ("TransformTrajectoryPlan", "PyTransformTrajectoryPlan"),
    ("RotatePlan", "PyRotatePlan"),
    ("ScalePlan", "PyScalePlan"),
    ("MultiVectorPlan", "PyMultiVectorPlan"),
    ("ImagePlan", "PyImagePlan"),
    ("ImageTrajectoryPlan", "PyImageTrajectoryPlan"),
    ("AutoImagePlan", "PyAutoImagePlan"),
    ("AutoImageTrajectoryPlan", "PyAutoImageTrajectoryPlan"),
    ("ReplicateCellPlan", "PyReplicateCellPlan"),
    ("XtalSymmPlan", "PyXtalSymmPlan"),
    ("VolumePlan", "PyVolumePlan"),
    ("StripPlan", "PyStripPlan"),
    ("StripTrajectoryPlan", "PyStripTrajectoryPlan"),
    ("MeanStructurePlan", "PyMeanStructurePlan"),
    ("AverageFramePlan", "PyAverageFramePlan"),
    ("MakeStructurePlan", "PyMakeStructurePlan"),
    ("CenterOfMassPlan", "PyCenterOfMassPlan"),
    ("CenterOfGeometryPlan", "PyCenterOfGeometryPlan"),
    ("DistanceToPointPlan", "PyDistanceToPointPlan"),
    ("DistanceToReferencePlan", "PyDistanceToReferencePlan"),
    ("PrincipalAxesPlan", "PyPrincipalAxesPlan"),
    ("AlignPlan", "PyAlignPlan"),
    ("SuperposePlan", "PySuperposePlan"),
    ("SuperposeTrajectoryPlan", "PySuperposeTrajectoryPlan"),
    ("RotationMatrixPlan", "PyRotationMatrixPlan"),
    ("AlignPrincipalAxisPlan", "PyAlignPrincipalAxisPlan"),
    ("MsdPlan", "PyMsdPlan"),
    ("AtomicCorrelationPlan", "PyAtomicCorrelationPlan"),
    ("VelocityAutoCorrPlan", "PyVelocityAutoCorrPlan"),
    ("VanHovePlan", "PyVanHovePlan"),
    ("RotAcfPlan", "PyRotAcfPlan"),
    ("ConductivityPlan", "PyConductivityPlan"),
    ("CurrentPlan", "PyCurrentPlan"),
    ("DielectricPlan", "PyDielectricPlan"),
    ("WaterOrderPlan", "PyWaterOrderPlan"),
    ("HydrationOrderPlan", "PyHydrationOrderPlan"),
    ("HydrophobicDefectPlan", "PyHydrophobicDefectPlan"),
    ("LipidLeafletPlan", "PyLipidLeafletPlan"),
    ("LipidCurvedLeafletPlan", "PyLipidCurvedLeafletPlan"),
    ("LipidZPositionPlan", "PyLipidZPositionPlan"),
    ("LipidZThicknessPlan", "PyLipidZThicknessPlan"),
    ("LipidZAnglePlan", "PyLipidZAnglePlan"),
    ("LipidAreaPlan", "PyLipidAreaPlan"),
    ("LipidFlipFlopPlan", "PyLipidFlipFlopPlan"),
    ("LipidNeighbourPlan", "PyLipidNeighbourPlan"),
    ("LipidLargestClusterPlan", "PyLipidLargestClusterPlan"),
    ("LipidMembraneThicknessPlan", "PyLipidMembraneThicknessPlan"),
    ("LipidRegistrationPlan", "PyLipidRegistrationPlan"),
    ("LipidMsdPlan", "PyLipidMsdPlan"),
    ("LipidSccPlan", "PyLipidSccPlan"),
    ("LipidNeighbourMatrixPlan", "PyLipidNeighbourMatrixPlan"),
    ("SolventOrientationPlan", "PySolventOrientationPlan"),
    ("SolventPolarizationPlan", "PySolventPolarizationPlan"),
    ("NematicOrderPlan", "PyNematicOrderPlan"),
    ("PotentialPlan", "PyPotentialPlan"),
    ("DipoleMomentPlan", "PyDipoleMomentPlan"),
    ("DipoleAlignmentPlan", "PyDipoleAlignmentPlan"),
    ("IonPairCorrelationPlan", "PyIonPairCorrelationPlan"),
    ("SaltBridgePlan", "PySaltBridgePlan"),
    ("StructureFactorPlan", "PyStructureFactorPlan"),
    ("RamaPlan", "PyRamaPlan"),
    ("WaterCountPlan", "PyWaterCountPlan"),
    ("CountInVoxelPlan", "PyCountInVoxelPlan"),
    ("DensityPlan", "PyDensityPlan"),
    ("LinearDensityPlan", "PyLinearDensityPlan"),
    ("DensityMapPlan", "PyDensityMapPlan"),
    ("VolmapPlan", "PyVolmapPlan"),
    ("FreeVolumePlan", "PyFreeVolumePlan"),
    ("BondiFfvPlan", "PyBondiFfvPlan"),
    ("EquipartitionPlan", "PyEquipartitionPlan"),
    ("CrossCorrelationPlan", "PyCrossCorrelationPlan"),
    ("WaveletPlan", "PyWaveletPlan"),
    ("SurfPlan", "PySurfPlan"),
    ("MolSurfPlan", "PyMolSurfPlan"),
    ("TorsionDiffusionPlan", "PyTorsionDiffusionPlan"),
    ("ToroidalDiffusionPlan", "PyToroidalDiffusionPlan"),
    ("MultiPuckerPlan", "PyMultiPuckerPlan"),
    ("NmrIredPlan", "PyNmrIredPlan"),
    ("HbondPlan", "PyHbondPlan"),
    ("RdfPlan", "PyRdfPlan"),
    ("EndToEndPlan", "PyEndToEndPlan"),
    ("ContourLengthPlan", "PyContourLengthPlan"),
    ("ChainRgPlan", "PyChainRgPlan"),
    ("BondLengthDistributionPlan", "PyBondLengthDistributionPlan"),
    ("BondAngleDistributionPlan", "PyBondAngleDistributionPlan"),
    ("PersistenceLengthPlan", "PyPersistenceLengthPlan"),
)

_OPTIONAL_CLASS_BINDINGS = (
    ("BundlePlan", "PyBundlePlan"),
    ("HelixPlan", "PyHelixPlan"),
    ("MdmatPlan", "PyMdmatPlan"),
    ("HelixOrientationPlan", "PyHelixOrientationPlan"),
    ("DockingPlan", "PyDockingPlan"),
    ("GistGridPlan", "PyGistGridPlan"),
    ("GistDirectPlan", "PyGistDirectPlan"),
    ("PairListDistancePlan", "PyPairListDistancePlan"),
    ("MultiDistancePlan", "PyMultiDistancePlan"),
    ("DistanceVectorPlan", "PyDistanceVectorPlan"),
    ("RadgyrPlan", "PyRadgyrPlan"),
    ("ShapeDescriptorsPlan", "PyShapeDescriptorsPlan"),
    ("DistanceCenterToPointPlan", "PyDistanceCenterToPointPlan"),
    ("DistanceCenterToReferencePlan", "PyDistanceCenterToReferencePlan"),
    ("PairDistDynamicPlan", "PyPairDistDynamicPlan"),
    ("PairDistanceExtremaPlan", "PyPairDistanceExtremaPlan"),
    ("MultiAnglePlan", "PyMultiAnglePlan"),
    ("DridPlan", "PyDridPlan"),
    ("RunningAveragePlan", "PyRunningAveragePlan"),
    ("RunningAverageTrajectoryPlan", "PyRunningAverageTrajectoryPlan"),
    ("KabschSanderPlan", "PyKabschSanderPlan"),
)

_OPTIONAL_FUNCTION_BINDINGS = (
    ("gist_apply_pme_scaling", "gist_apply_pme_scaling"),
    ("array_autocorrelation", "array_autocorrelation"),
    ("array_cross_correlation", "array_cross_correlation"),
    ("array_time_correlation", "array_time_correlation"),
    ("apply_orthorhombic_pbc_vectors", "apply_orthorhombic_pbc_vectors"),
    ("closest_gather_array", "closest_gather_array"),
    ("fluct_aggregate_array", "fluct_aggregate_array"),
    ("lowestcurve_array", "lowestcurve_array"),
    ("pair_distances_array", "pair_distances_array"),
    ("binned_statistic_2d_array", "binned_statistic_2d_array"),
    ("haar_details_array", "haar_details_array"),
    ("lipid_neighbour_composition_array", "lipid_neighbour_composition_array"),
    ("lipid_scd_chunk_array", "lipid_scd_chunk_array"),
    ("mode_corr_array", "mode_corr_array"),
    ("mode_trajout_array", "mode_trajout_array"),
    ("nearest_fill_grid_array", "nearest_fill_grid_array"),
    ("transition_stats_array", "transition_stats_array"),
    ("velocity_differences_array", "velocity_differences_array"),
)


def _binding_unavailable(name: str) -> str:
    return f"{name} binding unavailable in this build. Rebuild bindings with `maturin develop`."


def _make_missing_binding(name: str):
    class _MissingBinding:
        def __init__(self, *args, **kwargs):
            raise RuntimeError(_binding_unavailable(name))

    _MissingBinding.__name__ = f"Missing{name}"
    return _MissingBinding


def _make_missing_function(name: str):
    def _missing(*args, **kwargs):
        raise RuntimeError(_binding_unavailable(name))

    _missing.__name__ = name
    return _missing


def _register_missing_bindings(missing_type, missing_function) -> None:
    for public_name, _native_name in _REQUIRED_BINDINGS:
        globals()[public_name] = missing_type
    for public_name, _native_name in _OPTIONAL_CLASS_BINDINGS:
        globals()[public_name] = missing_type
    for public_name, _native_name in _OPTIONAL_FUNCTION_BINDINGS:
        globals()[public_name] = missing_function


try:
    from . import traj_py as traj_py

    for public_name, native_name in _REQUIRED_BINDINGS:
        binding = getattr(traj_py, native_name, None)
        if binding is None:
            raise ImportError(f"required binding unavailable: {native_name}")
        globals()[public_name] = binding

    for public_name, native_name in _OPTIONAL_CLASS_BINDINGS:
        binding = getattr(traj_py, native_name, None)
        globals()[public_name] = (
            binding if binding is not None else _make_missing_binding(public_name)
        )

    for public_name, native_name in _OPTIONAL_FUNCTION_BINDINGS:
        binding = getattr(traj_py, native_name, None)
        globals()[public_name] = (
            binding if binding is not None else _make_missing_function(public_name)
        )

    __rust_build_profile__ = getattr(traj_py, "__rust_build_profile__", "unknown")
    __rust_cuda_enabled__ = bool(getattr(traj_py, "__rust_cuda_enabled__", False))
    _IMPORT_ERROR = None
except (ImportError, OSError) as exc:  # pragma: no cover - allow CLI help without bindings
    _IMPORT_ERROR = exc
    traj_py = None
    __rust_build_profile__ = "unavailable"
    __rust_cuda_enabled__ = False

    def _missing(*_args, **_kwargs):
        raise RuntimeError(
            "warp-md Python bindings are unavailable. Run `maturin develop` or install warp-md."
        ) from _IMPORT_ERROR

    class _Missing:
        def __init__(self, *args, **kwargs):
            _missing(*args, **kwargs)

    _register_missing_bindings(_Missing, _missing)
from .builder import (
    charges_from_selections,
    charges_from_table,
    group_indices,
    group_types_from_selections,
)
from .analysis import (
    acorr,
    current,
    bundle,
    h2order,
    helixorient,
    helix,
    mdmat,
    hydorder,
    hydrophobic_defect_points,
    hydrophobic_defects,
    write_hydrophobic_defect_points,
    sorient,
    spol,
    potential,
    align,
    align_principal_axis,
    superpose,
    ArrayTrajectory,
    crank,
    dssp,
    dssp_allatoms,
    dssp_allresidues,
    kabsch_sander,
    rama,
    saltbr,
    energy_analysis,
    ene_decomp,
    esander,
    gist,
    GistConfig,
    GistResult,
    infraredspec,
    lipidscd,
    lipid_area,
    lipid_curved_leaflets,
    lipid_flip_flop,
    lipid_joint_density,
    lipid_largest_cluster,
    lipid_leaflets,
    lipid_membrane_thickness,
    lipid_msd,
    lipid_neighbours,
    lipid_neighbour_composition,
    lipid_neighbour_matrix,
    lipid_project_values,
    lipid_registration,
    lipid_scc,
    lipid_scc_weighted_average,
    lipid_z_angles,
    lipid_z_positions,
    lipid_z_thickness,
    rmsf,
    atomicfluct,
    bfactors,
    lie,
    distance_rmsd,
    pairwise_rmsd,
    cluster_trajectory,
    center,
    rotate,
    scale,
    transform,
    translate,
    covar,
    mwcovar,
    dist,
    correl,
    wavelet,
    mean_structure,
    make_structure,
    get_average_frame,
    gyrate,
    strip,
    radgyr,
    radgyr_tensor,
    shape_descriptors,
    principal_moments,
    asphericity,
    acylindricity,
    relative_shape_anisotropy,
    relative_shape_antisotropy,
    get_velocity,
    ired_vector_and_matrix,
    jcoupling,
    nh_order_parameters,
    calc_ired_vector_and_matrix,
    calc_nh_order_parameters,
    ti,
    timecorr,
    velocity_autocorrelation,
    vanhove,
    xcorr,
    pca,
    projection,
    analyze_modes,
    vector,
    vector_mask,
    rotation_matrix,
    angle,
    dihedral,
    distance,
    search_neighbors,
    symmrmsd,
    set_velocity,
    autoimage,
    fiximagedbonds,
    native_contacts,
    atom_map,
    check_structure,
    closest,
    closest_atom,
    count_in_voxel,
    dipole_moments,
    linear_density,
    lineardensity,
    compute_directors,
    compute_nematic_order,
    nematic_order,
    hbond,
    pairdist,
    mindist,
    maxdist,
    rdf,
    radial,
    runningavg,
    surf,
    molsurf,
    sasa,
    docking,
    docking_ligplot_svg,
    drid,
    pucker,
    rotdif,
    multipucker,
    xtalsymm,
)
from .pack import Box as PackBox
from .pack import Constraint as PackConstraint
from .pack import OutputSpec as PackOutputSpec
from .pack import PackConfig, PackResult, Structure as PackStructure
from .pack import export as pack_export
from .pack import parse_inp as pack_parse_inp
from .pack import run as pack_run
from .pack import run_inp as pack_run_inp
from .io import open_trajectory_auto, open_trajectory

__all__ = [
    "traj_py",
    "System",
    "Selection",
    "Trajectory",
    "open_trajectory_auto",
    "open_trajectory",
    "ArrayTrajectory",
    "RgPlan",
    "RadgyrPlan",
    "RadgyrTensorPlan",
    "ShapeDescriptorsPlan",
    "RmsdPlan",
    "SymmRmsdPlan",
    "DistanceRmsdPlan",
    "PairwiseRmsdPlan",
    "DridPlan",
    "RunningAveragePlan",
    "RunningAverageTrajectoryPlan",
    "KabschSanderPlan",
    "TrajectoryClusterPlan",
    "MatrixPlan",
    "PcaPlan",
    "AnalyzeModesPlan",
    "ProjectionPlan",
    "RmsdPerResPlan",
    "RmsfPlan",
    "BfactorsPlan",
    "AtomicAdpPlan",
    "AtomicFluctPlan",
    "DistancePlan",
    "DistanceCenterToPointPlan",
    "DistanceCenterToReferencePlan",
    "LowestCurvePlan",
    "VectorPlan",
    "GetVelocityPlan",
    "SetVelocityPlan",
    "PairwiseDistancePlan",
    "PairListDistancePlan",
    "PairDistPlan",
    "PairDistDynamicPlan",
    "AnglePlan",
    "MultiAnglePlan",
    "DihedralPlan",
    "MultiDihedralPlan",
    "PermuteDihedralsPlan",
    "DihedralRmsPlan",
    "PuckerPlan",
    "RotateDihedralPlan",
    "RotateDihedralTrajectoryPlan",
    "SetDihedralPlan",
    "SetDihedralTrajectoryPlan",
    "CheckChiralityPlan",
    "MindistPlan",
    "HausdorffPlan",
    "CheckStructurePlan",
    "AtomMapPlan",
    "FixImageBondsPlan",
    "FixImageBondsTrajectoryPlan",
    "RandomizeIonsPlan",
    "RandomizeIonsTrajectoryPlan",
    "ClosestAtomPlan",
    "SearchNeighborsPlan",
    "SearchNeighborListPlan",
    "WatershellPlan",
    "ClosestPlan",
    "ClosestCoordsPlan",
    "NativeContactsPlan",
    "CenterTrajectoryPlan",
    "CenterTrajectoryOutputPlan",
    "TranslatePlan",
    "TransformPlan",
    "TransformTrajectoryPlan",
    "RotatePlan",
    "ScalePlan",
    "MultiVectorPlan",
    "ImagePlan",
    "ImageTrajectoryPlan",
    "AutoImagePlan",
    "AutoImageTrajectoryPlan",
    "ReplicateCellPlan",
    "XtalSymmPlan",
    "VolumePlan",
    "StripPlan",
    "StripTrajectoryPlan",
    "MeanStructurePlan",
    "AverageFramePlan",
    "MakeStructurePlan",
    "CenterOfMassPlan",
    "CenterOfGeometryPlan",
    "DistanceToPointPlan",
    "DistanceToReferencePlan",
    "PrincipalAxesPlan",
    "AlignPlan",
    "SuperposePlan",
    "SuperposeTrajectoryPlan",
    "RotationMatrixPlan",
    "AlignPrincipalAxisPlan",
    "MsdPlan",
    "AtomicCorrelationPlan",
    "VelocityAutoCorrPlan",
    "VanHovePlan",
    "RotAcfPlan",
    "ConductivityPlan",
    "CurrentPlan",
    "DielectricPlan",
    "WaterOrderPlan",
    "BundlePlan",
    "HelixOrientationPlan",
    "HelixPlan",
    "LipidLeafletPlan",
    "LipidCurvedLeafletPlan",
    "LipidZPositionPlan",
    "LipidZThicknessPlan",
    "LipidZAnglePlan",
    "LipidAreaPlan",
    "LipidFlipFlopPlan",
    "LipidNeighbourPlan",
    "LipidLargestClusterPlan",
    "LipidMembraneThicknessPlan",
    "LipidRegistrationPlan",
    "LipidMsdPlan",
    "LipidSccPlan",
    "LipidNeighbourMatrixPlan",
    "MdmatPlan",
    "HydrationOrderPlan",
    "SolventOrientationPlan",
    "SolventPolarizationPlan",
    "NematicOrderPlan",
    "PotentialPlan",
    "DipoleAlignmentPlan",
    "DipoleMomentPlan",
    "IonPairCorrelationPlan",
    "SaltBridgePlan",
    "StructureFactorPlan",
    "RamaPlan",
    "DockingPlan",
    "GistGridPlan",
    "GistDirectPlan",
    "WaterCountPlan",
    "CountInVoxelPlan",
    "DensityPlan",
    "LinearDensityPlan",
    "VolmapPlan",
    "FreeVolumePlan",
    "HydrophobicDefectPlan",
    "BondiFfvPlan",
    "EquipartitionPlan",
    "CrossCorrelationPlan",
    "WaveletPlan",
    "SurfPlan",
    "MolSurfPlan",
    "TorsionDiffusionPlan",
    "ToroidalDiffusionPlan",
    "MultiPuckerPlan",
    "NmrIredPlan",
    "HbondPlan",
    "RdfPlan",
    "EndToEndPlan",
    "ContourLengthPlan",
    "ChainRgPlan",
    "BondLengthDistributionPlan",
    "BondAngleDistributionPlan",
    "PersistenceLengthPlan",
    "group_indices",
    "group_types_from_selections",
    "charges_from_selections",
    "charges_from_table",
    "crank",
    "align",
    "align_principal_axis",
    "superpose",
    "acorr",
    "current",
    "bundle",
    "h2order",
    "helixorient",
    "helix",
    "mdmat",
    "hydorder",
    "hydrophobic_defects",
    "hydrophobic_defect_points",
    "write_hydrophobic_defect_points",
    "sorient",
    "spol",
    "potential",
    "xcorr",
    "timecorr",
    "velocity_autocorrelation",
    "vanhove",
    "dssp",
    "dssp_allatoms",
    "dssp_allresidues",
    "kabsch_sander",
    "rama",
    "saltbr",
    "energy_analysis",
    "esander",
    "lie",
    "ene_decomp",
    "gist",
    "GistConfig",
    "GistResult",
    "infraredspec",
    "lipidscd",
    "lipid_area",
    "lipid_curved_leaflets",
    "lipid_flip_flop",
    "lipid_joint_density",
    "lipid_largest_cluster",
    "lipid_leaflets",
    "lipid_membrane_thickness",
    "lipid_msd",
    "lipid_neighbours",
    "lipid_neighbour_composition",
    "lipid_neighbour_matrix",
    "lipid_project_values",
    "lipid_registration",
    "lipid_scc",
    "lipid_scc_weighted_average",
    "lipid_z_angles",
    "lipid_z_positions",
    "lipid_z_thickness",
    "rmsf",
    "atomicfluct",
    "bfactors",
    "distance_rmsd",
    "pairwise_rmsd",
    "cluster_trajectory",
    "center",
    "translate",
    "transform",
    "rotate",
    "scale",
    "covar",
    "mwcovar",
    "dist",
    "correl",
    "wavelet",
    "mean_structure",
    "make_structure",
    "get_average_frame",
    "gyrate",
    "strip",
    "radgyr",
    "radgyr_tensor",
    "shape_descriptors",
    "principal_moments",
    "asphericity",
    "acylindricity",
    "relative_shape_anisotropy",
    "relative_shape_antisotropy",
    "get_velocity",
    "ired_vector_and_matrix",
    "jcoupling",
    "nh_order_parameters",
    "calc_ired_vector_and_matrix",
    "calc_nh_order_parameters",
    "ti",
    "pca",
    "projection",
    "analyze_modes",
    "vector",
    "vector_mask",
    "rotation_matrix",
    "angle",
    "dihedral",
    "distance",
    "search_neighbors",
    "symmrmsd",
    "set_velocity",
    "autoimage",
    "fiximagedbonds",
    "native_contacts",
    "atom_map",
    "check_structure",
    "closest",
    "closest_atom",
    "count_in_voxel",
    "dipole_moments",
    "lineardensity",
    "linear_density",
    "nematic_order",
    "compute_nematic_order",
    "compute_directors",
    "hbond",
    "pairdist",
    "mindist",
    "maxdist",
    "rdf",
    "radial",
    "runningavg",
    "surf",
    "molsurf",
    "sasa",
    "docking",
    "docking_ligplot_svg",
    "drid",
    "pucker",
    "rotdif",
    "multipucker",
    "xtalsymm",
    "PackBox",
    "PackConstraint",
    "PackOutputSpec",
    "PackConfig",
    "PackResult",
    "PackStructure",
    "pack_run",
    "pack_run_inp",
    "pack_parse_inp",
    "pack_export",
    "energy_decomposition",
]

energy_decomposition = ene_decomp
