"""Fallback agent contract catalog snapshot.

Generated from the Rust-native contract catalog. Do not edit by hand.
"""

CATALOG = {'analyses': [{'aliases': ['bond-angle'],
               'description': 'Bond angle distribution',
               'examples': [{'bins': 180,
                             'name': 'bond_angle_distribution',
                             'selection': 'polymer'}],
               'fields': {'bins': {'description': 'Number of angle bins',
                                   'minimum': 1,
                                   'semantic_type': 'integer',
                                   'type': 'integer'},
                          'degrees': {'default': True,
                                      'description': 'Use degrees (vs radians)',
                                      'semantic_type': 'boolean',
                                      'type': 'boolean'},
                          'selection': {'description': 'Atom selection for angle analysis',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'bond_angle_distribution',
               'optional_fields': ['degrees'],
               'outputs': [{'description': 'Bond angle distribution',
                            'fields': ['angle', 'probability'],
                            'format': 'npz',
                            'kind': 'histogram'}],
               'required_fields': ['selection', 'bins'],
               'tags': ['structural', 'bond']},
              {'aliases': ['bond-length'],
               'description': 'Bond length distribution',
               'examples': [{'bins': 100,
                             'name': 'bond_length_distribution',
                             'r_max': 0.2,
                             'selection': 'polymer'}],
               'fields': {'bins': {'description': 'Number of distance bins',
                                   'minimum': 1,
                                   'semantic_type': 'integer',
                                   'type': 'integer'},
                          'r_max': {'description': 'Maximum bond distance',
                                    'minimum': 0,
                                    'semantic_type': 'float',
                                    'type': 'float',
                                    'unit': 'nm'},
                          'selection': {'description': 'Atom selection for bond analysis',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'bond_length_distribution',
               'optional_fields': [],
               'outputs': [{'description': 'Bond length distribution',
                            'fields': ['distance_nm', 'probability'],
                            'format': 'npz',
                            'kind': 'histogram'}],
               'required_fields': ['selection', 'bins', 'r_max'],
               'tags': ['structural', 'bond']},
              {'aliases': ['bondi-ffv', 'ffv', 'fractional-free-volume'],
               'description': 'GROMACS-style free-volume Monte Carlo with Bondi radii. Reports raw '
                              'free-volume fraction and the Lourenco/GROMACS FFV convention FFV = '
                              '1 - scale * (1 - free_volume_fraction).',
               'examples': [{'bondi_scale': 1.3,
                             'name': 'bondi_ffv',
                             'ninsert_per_nm3': 1000,
                             'probe_radius': 0.0,
                             'seed': -1107428613,
                             'selection': 'not name QQQQ'}],
               'fields': {'bondi_scale': {'default': 1.3,
                                          'description': 'Homogeneity scale factor in FFV = 1 - '
                                                         'scale * (1 - free_volume_fraction)',
                                          'minimum': 0,
                                          'semantic_type': 'float',
                                          'type': 'float'},
                          'length_scale': {'default': 1.0,
                                           'description': 'Coordinate/box length scale',
                                           'semantic_type': 'float',
                                           'type': 'float'},
                          'ninsert_per_nm3': {'default': 1000,
                                              'description': 'Probe insertions per cubic nanometer',
                                              'minimum': 1,
                                              'semantic_type': 'integer',
                                              'type': 'integer'},
                          'probe_radius': {'default': 0.0,
                                           'description': 'Probe radius in Angstroms. 0.0 yields '
                                                          'true free volume.',
                                           'minimum': 0,
                                           'semantic_type': 'float',
                                           'type': 'float'},
                          'seed': {'default': 0,
                                   'description': 'Deterministic Monte Carlo seed',
                                   'semantic_type': 'integer',
                                   'type': 'integer'},
                          'selection': {'description': 'Atoms treated as excluded volume during '
                                                       'probe insertion',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'bondi_ffv',
               'optional_fields': ['bondi_scale',
                                   'probe_radius',
                                   'seed',
                                   'ninsert_per_nm3',
                                   'length_scale'],
               'outputs': [{'description': 'Per-frame Bondi/Lourenco free-volume metrics',
                            'fields': ['time',
                                       'total_volume_a3',
                                       'vdw_volume_a3',
                                       'raw_free_volume_a3',
                                       'raw_free_volume_fraction',
                                       'fractional_free_volume',
                                       'density_g_cm3',
                                       'molar_mass_dalton',
                                       'bondi_scale'],
                            'format': 'json',
                            'kind': 'table'}],
               'required_fields': ['selection'],
               'tags': ['polymer', 'free-volume', 'bondi', 'gromacs-parity']},
              {'aliases': ['chain-rg'],
               'description': 'Radius of gyration per chain/molecule',
               'examples': [{'name': 'chain_rg', 'selection': 'polymer'}],
               'fields': {'selection': {'description': 'Polymer atom selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'chain_rg',
               'optional_fields': [],
               'outputs': [{'description': 'Rg per chain',
                            'fields': ['chain_id', 'rg_nm'],
                            'format': 'npz',
                            'kind': 'table'}],
               'required_fields': ['selection'],
               'tags': ['structural', 'polymer']},
              {'aliases': ['electrical-conductivity'],
               'description': 'Electrical conductivity via Einstein relation',
               'examples': [{'charges': 'by_resname',
                             'name': 'conductivity',
                             'selection': 'resname Na or resname CL',
                             'temperature': 300.0}],
               'fields': {'charges': {'choices': ['by_atom', 'by_resname', 'by_name'],
                                      'description': 'Charge specification method',
                                      'semantic_type': 'charges',
                                      'type': 'string'},
                          'selection': {'description': 'Ion selection for conductivity',
                                        'semantic_type': 'selection',
                                        'type': 'string'},
                          'temperature': {'description': 'Temperature in Kelvin',
                                          'minimum': 0,
                                          'semantic_type': 'float',
                                          'type': 'float',
                                          'unit': 'K'},
                          'transference': {'default': False,
                                           'description': 'Compute transference numbers',
                                           'semantic_type': 'boolean',
                                           'type': 'boolean'}},
               'name': 'conductivity',
               'optional_fields': ['group_by',
                                   'transference',
                                   'length_scale',
                                   'frame_decimation',
                                   'dt_decimation',
                                   'time_binning',
                                   'lag_mode',
                                   'max_lag'],
               'outputs': [{'description': 'Conductivity vs lag time',
                            'fields': ['lag_time_ps', 'conductivity_S_per_cm'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection', 'charges', 'temperature'],
               'tags': ['dynamic', 'electrostatics', 'transport']},
              {'aliases': ['contour-length'],
               'description': 'Contour length (bond path length) for polymers',
               'examples': [{'name': 'contour_length', 'selection': 'polymer'}],
               'fields': {'selection': {'description': 'Polymer atom selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'contour_length',
               'optional_fields': [],
               'outputs': [{'description': 'Contour length vs time',
                            'fields': ['time_ps', 'contour_nm'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection'],
               'tags': ['structural', 'polymer']},
              {'aliases': ['number-density', 'mass-density'],
               'description': 'Density profile along a direction',
               'examples': [{'direction': 'z', 'mask': 'resname SOL', 'name': 'density'}],
               'fields': {'delta': {'description': 'Bin width',
                                    'minimum': 0,
                                    'semantic_type': 'float',
                                    'type': 'float'},
                          'density_type': {'choices': ['number', 'mass', 'charge'],
                                           'description': 'Type of density (number, mass, charge)',
                                           'semantic_type': 'string',
                                           'type': 'string'},
                          'direction': {'description': 'Direction for profile (x, y, z, or normal)',
                                        'semantic_type': 'string',
                                        'type': 'string'},
                          'mask': {'description': 'Atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'}},
               'name': 'density',
               'optional_fields': ['mask',
                                   'density_type',
                                   'delta',
                                   'direction',
                                   'cutoff',
                                   'center'],
               'outputs': [{'description': 'Density vs position',
                            'fields': ['position', 'density'],
                            'format': 'npz',
                            'kind': 'profile'}],
               'required_fields': [],
               'tags': ['structural', 'spatial']},
              {'aliases': ['dielectric-constant'],
               'description': 'Dielectric constant from dipole fluctuations',
               'examples': [{'charges': 'by_resname',
                             'name': 'dielectric',
                             'selection': 'resname SOL'}],
               'fields': {'charges': {'description': 'Charge specification method',
                                      'semantic_type': 'charges',
                                      'type': 'string'},
                          'make_whole': {'default': True,
                                         'description': 'Reconstruct grouped molecules across '
                                                        'periodic boundaries',
                                         'semantic_type': 'boolean',
                                         'type': 'boolean'},
                          'selection': {'description': 'Molecule selection for dielectric',
                                        'semantic_type': 'selection',
                                        'type': 'string'},
                          'temperature': {'default': 300.0,
                                          'description': 'Simulation temperature in Kelvin',
                                          'minimum': 0.0,
                                          'semantic_type': 'float',
                                          'type': 'float',
                                          'unit': 'K'}},
               'name': 'dielectric',
               'optional_fields': ['group_by', 'length_scale', 'temperature', 'make_whole'],
               'outputs': [{'description': 'Dielectric constant and dipole moment',
                            'fields': ['dielectric_constant', 'dipole_moment_debye'],
                            'format': 'npz',
                            'kind': 'artifact'}],
               'required_fields': ['selection', 'charges'],
               'tags': ['electrostatics']},
              {'aliases': ['diffusion-coefficient'],
               'description': 'Diffusion coefficient from MSD slope',
               'examples': [{'mask': 'resname SOL', 'name': 'diffusion'}],
               'fields': {'individual': {'default': False,
                                         'description': 'Compute per-species diffusion',
                                         'semantic_type': 'boolean',
                                         'type': 'boolean'},
                          'mask': {'description': 'Atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'tstep': {'description': 'Time step in picoseconds',
                                    'semantic_type': 'float',
                                    'type': 'float'}},
               'name': 'diffusion',
               'optional_fields': ['mask', 'tstep', 'individual'],
               'outputs': [{'description': 'Diffusion coefficient and MSD data',
                            'fields': ['diffusion_coefficient', 'msd_data'],
                            'format': 'npz',
                            'kind': 'artifact'}],
               'required_fields': [],
               'tags': ['dynamic', 'transport', 'diffusion']},
              {'aliases': ['dipole-alignment'],
               'description': 'Dipole-dipole alignment correlation',
               'examples': [{'charges': 'by_resname',
                             'name': 'dipole_alignment',
                             'selection': 'resname SOL'}],
               'fields': {'charges': {'description': 'Charge specification method',
                                      'semantic_type': 'charges',
                                      'type': 'string'},
                          'selection': {'description': 'Molecule selection for dipole alignment',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'dipole_alignment',
               'optional_fields': ['group_by', 'length_scale'],
               'outputs': [{'description': 'Dipole alignment distribution',
                            'fields': ['cos_theta', 'probability'],
                            'format': 'npz',
                            'kind': 'histogram'}],
               'required_fields': ['selection', 'charges'],
               'tags': ['electrostatics']},
              {'aliases': ['docking-analysis'],
               'description': 'Docking pose analysis (protein-ligand interactions)',
               'examples': [{'ligand_mask': 'resname LIG',
                             'name': 'docking',
                             'receptor_mask': 'protein'}],
               'fields': {'clash_cutoff': {'description': 'Clash detection cutoff',
                                           'minimum': 0,
                                           'semantic_type': 'float',
                                           'type': 'float',
                                           'unit': 'nm'},
                          'close_contact_cutoff': {'description': 'Close contact distance cutoff',
                                                   'minimum': 0,
                                                   'semantic_type': 'float',
                                                   'type': 'float',
                                                   'unit': 'nm'},
                          'hydrogen_bond_cutoff': {'description': 'Hydrogen bond distance cutoff',
                                                   'minimum': 0,
                                                   'semantic_type': 'float',
                                                   'type': 'float',
                                                   'unit': 'nm'},
                          'hydrophobic_cutoff': {'description': 'Hydrophobic interaction cutoff',
                                                 'minimum': 0,
                                                 'semantic_type': 'float',
                                                 'type': 'float',
                                                 'unit': 'nm'},
                          'ligand_mask': {'description': 'Ligand atom mask',
                                          'semantic_type': 'mask',
                                          'type': 'string'},
                          'receptor_mask': {'description': 'Receptor atom mask',
                                            'semantic_type': 'mask',
                                            'type': 'string'}},
               'name': 'docking',
               'optional_fields': ['close_contact_cutoff',
                                   'hydrophobic_cutoff',
                                   'hydrogen_bond_cutoff',
                                   'clash_cutoff',
                                   'salt_bridge_cutoff',
                                   'halogen_bond_cutoff',
                                   'metal_coordination_cutoff',
                                   'cation_pi_cutoff',
                                   'pi_pi_cutoff',
                                   'hbond_min_angle_deg',
                                   'donor_hydrogen_cutoff',
                                   'allow_missing_hydrogen',
                                   'length_scale',
                                   'frame_indices',
                                   'max_events_per_frame'],
               'outputs': [{'description': 'Docking interaction summary',
                            'fields': ['interaction_type', 'count', 'details'],
                            'format': 'json',
                            'kind': 'table'}],
               'required_fields': ['receptor_mask', 'ligand_mask'],
               'tags': ['docking', 'protein', 'structural']},
              {'aliases': ['secondary-structure'],
               'description': 'Protein secondary structure assignment (DSSP)',
               'examples': [{'mask': 'protein', 'name': 'dssp'}],
               'fields': {'mask': {'description': 'Protein atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'simplified': {'default': False,
                                         'description': 'Use simplified 3-state classification',
                                         'semantic_type': 'boolean',
                                         'type': 'boolean'}},
               'name': 'dssp',
               'optional_fields': ['mask', 'simplified'],
               'outputs': [{'description': 'Secondary structure per residue',
                            'fields': ['residue', 'structure'],
                            'format': 'npz',
                            'kind': 'table'}],
               'required_fields': [],
               'tags': ['protein', 'structural']},
              {'aliases': ['alpha-helix', 'helix-geometry'],
               'description': 'Alpha-helix fragment detection and fitted helix metrics',
               'examples': [{'name': 'helix', 'selection': 'protein and backbone'}],
               'fields': {'check_each_frame': {'default': False,
                                               'description': 'Redetect the helical fragment on every frame',
                                               'semantic_type': 'boolean',
                                               'type': 'boolean'},
                          'fit': {'default': True,
                                  'description': 'Fit the fragment to an ideal alpha helix before reporting geometry',
                                  'semantic_type': 'boolean',
                                  'type': 'boolean'},
                          'residue_end': {'description': 'Inclusive residue id for a fixed helix range',
                                          'semantic_type': 'int',
                                          'type': 'integer'},
                          'residue_start': {'description': 'Inclusive residue id for a fixed helix range',
                                            'semantic_type': 'int',
                                            'type': 'integer'},
                          'selection': {'description': 'Protein backbone selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'helix',
               'optional_fields': ['selection',
                                   'fit',
                                   'check_each_frame',
                                   'residue_start',
                                   'residue_end',
                                   'length_scale'],
               'outputs': [{'description': 'Per-frame helix geometry and per-residue occupancy',
                            'fields': ['time_ps',
                                       'fragment_start',
                                       'fragment_end',
                                       'radius',
                                       'twist',
                                       'rise',
                                       'length',
                                       'rmsd',
                                       'helicity_fraction'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': [],
               'tags': ['protein', 'secondary', 'structural']},
              {'aliases': ['end-to-end-distance'],
               'description': 'End-to-end distance for polymers',
               'examples': [{'name': 'end_to_end', 'selection': 'polymer'}],
               'fields': {'selection': {'description': 'Polymer atom selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'end_to_end',
               'optional_fields': [],
               'outputs': [{'description': 'End-to-end distance vs time',
                            'fields': ['time_ps', 'end_to_end_nm'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection'],
               'tags': ['structural', 'polymer']},
              {'aliases': ['kinetic-energy', 'ke-distribution'],
               'description': 'Kinetic energy distribution by group',
               'examples': [{'name': 'equipartition', 'selection': 'protein'}],
               'fields': {'group_by': {'description': 'How to group atoms',
                                       'semantic_type': 'string',
                                       'type': 'string'},
                          'selection': {'description': 'Atom selection for kinetic energy',
                                        'semantic_type': 'selection',
                                        'type': 'string'},
                          'velocity_scale': {'description': 'Velocity scaling factor',
                                             'semantic_type': 'float',
                                             'type': 'float'}},
               'name': 'equipartition',
               'optional_fields': ['group_by', 'velocity_scale', 'length_scale'],
               'outputs': [{'description': 'Kinetic energy per group',
                            'fields': ['group', 'kinetic_energy_kJ_per_mol'],
                            'format': 'npz',
                            'kind': 'table'}],
               'required_fields': ['selection'],
               'tags': ['thermodynamic']},
              {'aliases': ['free-volume', 'free-volume-grid', 'voxel-free-volume'],
               'description': 'Voxel-grid free-volume fraction. Useful for spatial void maps, not '
                              'Bondi-style polymer FFV.',
               'examples': [{'box_unit': [1.0, 1.0, 1.0],
                             'center_selection': 'protein',
                             'name': 'free_volume',
                             'note': 'Explicit parameters',
                             'probe_radius': 0.5,
                             'region_size': [30.0, 30.0, 30.0],
                             'selection': 'protein'},
                            {'center_selection': 'protein',
                             'name': 'free_volume_auto',
                             'note': 'Auto-detects region_size from bounding box, defaults '
                                     'box_unit to 1.0 Å',
                             'selection': 'protein'}],
               'fields': {'box_unit': {'default': [1.0, 1.0, 1.0],
                                       'description': 'Voxel size (x, y, z) in Angstroms. Defaults '
                                                      'to [1.0, 1.0, 1.0] if not specified.',
                                       'semantic_type': 'vector',
                                       'type': 'array'},
                          'center_selection': {'description': 'Selection used to define grid '
                                                              'origin and auto-detect region_size',
                                               'semantic_type': 'selection',
                                               'type': 'string'},
                          'length_scale': {'default': 1.0,
                                           'description': 'Coordinate length scale',
                                           'semantic_type': 'float',
                                           'type': 'float'},
                          'probe_radius': {'description': 'Probe radius that expands occupied '
                                                          'volume',
                                           'minimum': 0,
                                           'semantic_type': 'float',
                                           'type': 'float'},
                          'region_size': {'description': 'Region extents (x, y, z) in Angstroms. '
                                                         'Auto-detected from center_selection '
                                                         'bounding box with 10%% padding if not '
                                                         'specified.',
                                          'semantic_type': 'vector',
                                          'type': 'array'},
                          'selection': {'description': 'Atoms treated as occupied volume',
                                        'semantic_type': 'selection',
                                        'type': 'string'},
                          'shift': {'description': 'Shift for centered coordinates',
                                    'semantic_type': 'vector',
                                    'type': 'array'}},
               'name': 'free_volume',
               'optional_fields': ['box_unit',
                                   'region_size',
                                   'probe_radius',
                                   'shift',
                                   'length_scale'],
               'outputs': [{'description': 'Per-voxel free-volume fraction statistics',
                            'fields': ['dims', 'mean', 'std', 'first', 'last', 'min', 'max'],
                            'format': 'npz',
                            'kind': 'grid'}],
               'required_fields': ['selection', 'center_selection'],
               'tags': ['spatial', 'grid', 'void', 'solvation']},
              {'aliases': ['grid-inhomogeneous-solvation-theory'],
               'description': 'Grid inhomogeneous solvation theory (water thermodynamics)',
               'examples': [{'name': 'gist', 'solute': 'protein', 'solvent': 'resname SOL'}],
               'fields': {'solute': {'description': 'Solute selection',
                                     'semantic_type': 'selection',
                                     'type': 'string'},
                          'solvent': {'description': 'Solvent selection',
                                      'semantic_type': 'selection',
                                      'type': 'string'}},
               'name': 'gist',
               'optional_fields': [],
               'outputs': [{'description': '3D thermodynamic maps',
                            'fields': ['energy', 'entropy'],
                            'format': 'npz',
                            'kind': 'grid'}],
               'required_fields': ['solute', 'solvent'],
               'tags': ['thermodynamic', 'solvent', 'grid']},
              {'aliases': ['hydrogen-bond'],
               'description': 'Hydrogen bond analysis',
               'examples': [{'acceptors': 'resname SOL and name O',
                             'dist_cutoff': 0.35,
                             'donors': 'resname SOL and name OH',
                             'name': 'hbond'}],
               'fields': {'acceptors': {'description': 'Hydrogen bond acceptor selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'},
                          'angle_cutoff': {'description': 'Angle cutoff in degrees',
                                           'maximum': 180,
                                           'minimum': 0,
                                           'semantic_type': 'float',
                                           'type': 'float',
                                           'unit': 'degrees'},
                          'dist_cutoff': {'description': 'Distance cutoff for H-bond',
                                          'minimum': 0,
                                          'semantic_type': 'float',
                                          'type': 'float',
                                          'unit': 'nm'},
                          'donors': {'description': 'Hydrogen bond donor selection',
                                     'semantic_type': 'selection',
                                     'type': 'string'},
                          'hydrogens': {'description': 'Hydrogen atom selection (for angle '
                                                       'criteria)',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'hbond',
               'optional_fields': ['hydrogens', 'angle_cutoff'],
               'outputs': [{'description': 'Hydrogen bond count vs time',
                            'fields': ['time_ps', 'hbond_count'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['donors', 'acceptors', 'dist_cutoff'],
               'tags': ['structural', 'solvent']},
              {'aliases': ['ion-pair-correlation', 'ion-pair'],
               'description': 'Ion pair lifetime and correlation analysis',
               'examples': [{'name': 'ion_pair_correlation',
                             'rclust_ani': 0.35,
                             'rclust_cat': 0.35,
                             'selection': 'resname Na or resname CL'}],
               'fields': {'anion_type': {'description': 'Anion residue name',
                                         'semantic_type': 'string',
                                         'type': 'string'},
                          'cation_type': {'description': 'Cation residue name',
                                          'semantic_type': 'string',
                                          'type': 'string'},
                          'max_cluster': {'description': 'Maximum cluster size',
                                          'minimum': 1,
                                          'semantic_type': 'integer',
                                          'type': 'integer'},
                          'rclust_ani': {'description': 'Anion clustering cutoff distance',
                                         'minimum': 0,
                                         'semantic_type': 'float',
                                         'type': 'float',
                                         'unit': 'nm'},
                          'rclust_cat': {'description': 'Cation clustering cutoff distance',
                                         'minimum': 0,
                                         'semantic_type': 'float',
                                         'type': 'float',
                                         'unit': 'nm'},
                          'selection': {'description': 'Ion selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'ion_pair_correlation',
               'optional_fields': ['group_by',
                                   'cation_type',
                                   'anion_type',
                                   'max_cluster',
                                   'length_scale',
                                   'lag_mode',
                                   'max_lag'],
               'outputs': [{'description': 'Ion pair correlation function',
                            'fields': ['lag_time_ps', 'correlation'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection', 'rclust_cat', 'rclust_ani'],
               'tags': ['electrostatics', 'dynamic']},
              {'aliases': ['j-coupling', 'scalar-coupling'],
               'description': 'J-coupling constants from dihedral angles',
               'examples': [{'dihedrals': [[1, 2, 3, 4], [5, 6, 7, 8]], 'name': 'jcoupling'}],
               'fields': {'dihedrals': {'description': 'Dihedral atom indices (quadruples)',
                                        'semantic_type': 'vector',
                                        'type': 'array'},
                          'karplus': {'description': 'Karplus parameterization',
                                      'semantic_type': 'string',
                                      'type': 'string'},
                          'kfile': {'description': 'Path to Karplus parameter file',
                                    'semantic_type': 'path',
                                    'type': 'path'}},
               'name': 'jcoupling',
               'optional_fields': ['karplus', 'kfile', 'phase_deg', 'length_scale', 'pbc'],
               'outputs': [{'description': 'J-coupling per dihedral',
                            'fields': ['dihedral', 'j_coupling_hz'],
                            'format': 'npz',
                            'kind': 'table'}],
               'required_fields': ['dihedrals'],
               'tags': ['nmr']},
              {'aliases': ['molecular-surface'],
               'description': 'Molecular surface area (Connolly)',
               'examples': [{'mask': 'protein', 'name': 'molsurf'}],
               'fields': {'mask': {'description': 'Atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'probe_radius': {'description': 'Probe radius',
                                           'minimum': 0,
                                           'semantic_type': 'float',
                                           'type': 'float',
                                           'unit': 'nm'}},
               'name': 'molsurf',
               'optional_fields': ['mask', 'algorithm', 'probe_radius', 'radii'],
               'outputs': [{'description': 'Molecular surface area vs time',
                            'fields': ['time_ps', 'surface_area_nm2'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': [],
               'tags': ['structural', 'surface']},
              {'aliases': ['mean-square-displacement'],
               'description': 'Mean square displacement - diffusion analysis',
               'examples': [{'name': 'msd', 'selection': 'resname CL and name NA'}],
               'fields': {'axis': {'description': '3D vector for directional MSD (x, y, z)',
                                   'semantic_type': 'vector',
                                   'type': 'array'},
                          'group_by': {'default': 'resid',
                                       'description': 'How to group atoms (resid, molecule, etc.)',
                                       'semantic_type': 'string',
                                       'type': 'string'},
                          'lag_mode': {'choices': ['linear', 'log', 'ring'],
                                       'default': 'linear',
                                       'description': 'Lag computation mode',
                                       'semantic_type': 'string',
                                       'type': 'string'},
                          'length_scale': {'default': 1.0,
                                           'description': 'Length unit conversion factor (nm per '
                                                          'unit)',
                                           'semantic_type': 'float',
                                           'type': 'float'},
                          'max_lag': {'description': 'Maximum lag time in frames',
                                      'minimum': 1,
                                      'semantic_type': 'integer',
                                      'type': 'integer'},
                          'selection': {'description': 'Atom selection for MSD calculation',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'msd',
               'optional_fields': ['group_by',
                                   'axis',
                                   'length_scale',
                                   'frame_decimation',
                                   'dt_decimation',
                                   'time_binning',
                                   'lag_mode',
                                   'max_lag',
                                   'memory_budget_bytes',
                                   'multi_tau_m',
                                   'multi_tau_levels'],
               'outputs': [{'description': 'MSD vs lag time',
                            'fields': ['lag_time_ps', 'msd_nm2'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection'],
               'tags': ['dynamic', 'diffusion', 'transport']},
              {'aliases': ['native-contacts', 'q-value'],
               'description': 'Native contact analysis (folding)',
               'examples': [{'mask': 'protein', 'name': 'native_contacts'}],
               'fields': {'distance': {'description': 'Contact distance cutoff',
                                       'minimum': 0,
                                       'semantic_type': 'float',
                                       'type': 'float',
                                       'unit': 'nm'},
                          'mask': {'description': 'First atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'mask2': {'description': 'Second atom mask',
                                    'semantic_type': 'mask',
                                    'type': 'string'},
                          'maxdist': {'description': 'Maximum contact distance',
                                      'minimum': 0,
                                      'semantic_type': 'float',
                                      'type': 'float',
                                      'unit': 'nm'},
                          'mindist': {'description': 'Minimum contact distance',
                                      'minimum': 0,
                                      'semantic_type': 'float',
                                      'type': 'float',
                                      'unit': 'nm'}},
               'name': 'native_contacts',
               'optional_fields': ['mask',
                                   'mask2',
                                   'ref',
                                   'distance',
                                   'mindist',
                                   'maxdist',
                                   'image'],
               'outputs': [{'description': 'Native contacts vs time',
                            'fields': ['time_ps', 'native_contacts', 'q_value'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': [],
               'tags': ['structural', 'protein', 'folding']},
              {'aliases': ['nmr-order-parameters'],
               'description': 'NMR NH order parameters',
               'examples': [{'name': 'nmr', 'selection': 'protein'}],
               'fields': {'method': {'description': 'Computation method',
                                     'semantic_type': 'string',
                                     'type': 'string'},
                          'order': {'default': 2,
                                    'description': 'Order parameter (2 for S^2)',
                                    'semantic_type': 'integer',
                                    'type': 'integer'},
                          'selection': {'description': 'NH vector selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'},
                          'vector_pairs': {'description': 'Vector pair specification',
                                           'semantic_type': 'string',
                                           'type': 'string'}},
               'name': 'nmr',
               'optional_fields': ['vector_pairs',
                                   'method',
                                   'order',
                                   'tstep',
                                   'tcorr',
                                   'length_scale',
                                   'pbc'],
               'outputs': [{'description': 'Order parameters per residue',
                            'fields': ['residue', 'order_parameter'],
                            'format': 'npz',
                            'kind': 'table'}],
               'required_fields': ['selection'],
               'tags': ['nmr', 'protein']},
              {'aliases': ['principal-component-analysis', 'pca-analysis'],
               'description': 'Principal component analysis of atomic fluctuations',
               'examples': [{'mask': 'protein and name CA', 'n_vecs': 10, 'name': 'pca'}],
               'fields': {'fit': {'default': True,
                                  'description': 'Fit to average structure',
                                  'semantic_type': 'boolean',
                                  'type': 'boolean'},
                          'mask': {'description': 'Atom mask for PCA',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'n_vecs': {'description': 'Number of eigenvectors to compute',
                                     'minimum': 1,
                                     'semantic_type': 'integer',
                                     'type': 'integer'}},
               'name': 'pca',
               'optional_fields': ['n_vecs', 'fit', 'ref', 'ref_mask'],
               'outputs': [{'description': 'PCA eigendecomposition results',
                            'fields': ['eigenvalues', 'eigenvectors', 'projections'],
                            'format': 'npz',
                            'kind': 'artifact'}],
               'required_fields': ['mask'],
               'tags': ['structural', 'protein']},
              {'aliases': ['persistence-length'],
               'description': 'Polymer persistence length from bond vectors',
               'examples': [{'name': 'persistence_length', 'selection': 'polymer'}],
               'fields': {'selection': {'description': 'Polymer backbone selection',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'persistence_length',
               'optional_fields': [],
               'outputs': [{'description': 'Persistence length',
                            'fields': ['persistence_length_nm'],
                            'format': 'npz',
                            'kind': 'artifact'}],
               'required_fields': ['selection'],
               'tags': ['structural', 'polymer']},
              {'aliases': ['pca-projection'],
               'description': 'Project trajectory onto PCA eigenvectors',
               'examples': [{'mask': 'protein and name CA', 'n_vecs': 3, 'name': 'projection'}],
               'fields': {'eigenvec': {'description': 'Path to eigenvector file',
                                       'semantic_type': 'path',
                                       'type': 'path'},
                          'mask': {'description': 'Atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'n_vecs': {'description': 'Number of eigenvectors',
                                     'minimum': 1,
                                     'semantic_type': 'integer',
                                     'type': 'integer'}},
               'name': 'projection',
               'optional_fields': ['eigenvec', 'n_vecs', 'fit', 'ref', 'ref_mask'],
               'outputs': [{'description': 'PCA projections vs time',
                            'fields': ['time_ps', 'pc1', 'pc2', '...'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['mask'],
               'tags': ['structural', 'protein']},
              {'aliases': ['radial-distribution-function', 'pair-distribution'],
               'description': 'Radial distribution function g(r)',
               'examples': [{'bins': 200,
                             'name': 'rdf',
                             'r_max': 1.0,
                             'sel_a': 'resname SOL and name OW',
                             'sel_b': 'resname SOL and name OW'}],
               'fields': {'bins': {'default': 200,
                                   'description': 'Number of r bins',
                                   'minimum': 1,
                                   'semantic_type': 'integer',
                                   'type': 'integer'},
                          'pbc': {'default': True,
                                  'description': 'Apply periodic boundary conditions',
                                  'semantic_type': 'boolean',
                                  'type': 'boolean'},
                          'r_max': {'description': 'Maximum r distance',
                                    'minimum': 0,
                                    'semantic_type': 'float',
                                    'type': 'float',
                                    'unit': 'nm'},
                          'sel_a': {'description': 'Selection for group A',
                                    'semantic_type': 'selection',
                                    'type': 'string'},
                          'sel_b': {'description': 'Selection for group B',
                                    'semantic_type': 'selection',
                                    'type': 'string'}},
               'name': 'rdf',
               'optional_fields': ['pbc'],
               'outputs': [{'description': 'RDF g(r) vs distance',
                            'fields': ['r_nm', 'gr'],
                            'format': 'npz',
                            'kind': 'histogram'}],
               'required_fields': ['sel_a', 'sel_b', 'bins', 'r_max'],
               'tags': ['structural', 'solvent', 'distribution']},
              {'aliases': ['radius-of-gyration'],
               'description': 'Radius of gyration - measure of polymer compactness',
               'examples': [{'mass_weighted': True, 'name': 'rg', 'selection': 'protein'}],
               'fields': {'mass_weighted': {'default': False,
                                            'description': 'Use mass-weighted coordinates',
                                            'semantic_type': 'boolean',
                                            'type': 'boolean'},
                          'selection': {'description': 'Atom selection for Rg calculation',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'rg',
               'optional_fields': ['mass_weighted'],
               'outputs': [{'description': 'Time series of radius of gyration values',
                            'fields': ['time_ps', 'rg_nm'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection'],
               'tags': ['structural', 'polymer', 'protein']},
              {'aliases': ['root-mean-square-deviation'],
               'description': 'Root mean square deviation from reference structure',
               'examples': [{'align': True,
                             'name': 'rmsd',
                             'reference': 0,
                             'selection': 'protein and name CA'}],
               'fields': {'align': {'default': True,
                                    'description': 'Align to reference before RMSD calculation',
                                    'semantic_type': 'boolean',
                                    'type': 'boolean'},
                          'reference': {'default': 0,
                                        'description': 'Reference frame index (0-based)',
                                        'minimum': 0,
                                        'semantic_type': 'integer',
                                        'type': 'integer'},
                          'selection': {'description': 'Atom selection for RMSD calculation',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'rmsd',
               'optional_fields': ['reference', 'align'],
               'outputs': [{'description': 'Time series of RMSD values',
                            'fields': ['time_ps', 'rmsd_nm'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection'],
               'tags': ['structural', 'protein']},
              {'aliases': ['root-mean-square-fluctuation'],
               'description': 'Root mean square fluctuation (per-atom mobility)',
               'examples': [{'byres': True, 'mask': 'protein and name CA', 'name': 'rmsf'}],
               'fields': {'bymask': {'description': 'Mask for aggregation',
                                     'semantic_type': 'mask',
                                     'type': 'string'},
                          'byres': {'default': False,
                                    'description': 'Aggregate by residue',
                                    'semantic_type': 'boolean',
                                    'type': 'boolean'},
                          'calcadp': {'default': False,
                                      'description': 'Calculate ADP (B-factors)',
                                      'semantic_type': 'boolean',
                                      'type': 'boolean'},
                          'mask': {'description': 'Atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'}},
               'name': 'rmsf',
               'optional_fields': ['mask', 'byres', 'bymask', 'calcadp', 'length_scale'],
               'outputs': [{'description': 'RMSF per atom/residue',
                            'fields': ['atom', 'rmsf_nm'],
                            'format': 'npz',
                            'kind': 'table'}],
               'required_fields': [],
               'tags': ['structural', 'protein']},
              {'aliases': ['rotational-autocorrelation', 'rotational-acf'],
               'description': 'Rotational autocorrelation function',
               'examples': [{'name': 'rotacf',
                             'orientation': [0, 1, 2],
                             'selection': 'resname MEOH and name OH'}],
               'fields': {'max_lag': {'description': 'Maximum lag time in frames',
                                      'minimum': 1,
                                      'semantic_type': 'integer',
                                      'type': 'integer'},
                          'orientation': {'description': 'Vector indices for orientation (2 or 3 '
                                                         'atoms)',
                                          'semantic_type': 'vector',
                                          'type': 'array'},
                          'p2_legendre': {'default': True,
                                          'description': 'Use second Legendre polynomial',
                                          'semantic_type': 'boolean',
                                          'type': 'boolean'},
                          'selection': {'description': 'Atom selection for rotational ACF',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'rotacf',
               'optional_fields': ['group_by',
                                   'p2_legendre',
                                   'length_scale',
                                   'frame_decimation',
                                   'dt_decimation',
                                   'time_binning',
                                   'lag_mode',
                                   'max_lag'],
               'outputs': [{'description': 'Rotational ACF vs lag time',
                            'fields': ['lag_time_ps', 'acf'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['selection', 'orientation'],
               'tags': ['dynamic', 'rotational']},
              {'aliases': ['structure-factor', 'sk'],
               'description': 'Static structure factor S(q)',
               'examples': [{'bins': 200,
                             'name': 'structure_factor',
                             'q_bins': 200,
                             'q_max': 30.0,
                             'r_max': 1.0,
                             'selection': 'resname SOL'}],
               'fields': {'bins': {'description': 'Number of real-space bins',
                                   'minimum': 1,
                                   'semantic_type': 'integer',
                                   'type': 'integer'},
                          'pbc': {'default': True,
                                  'description': 'Apply periodic boundary conditions',
                                  'semantic_type': 'boolean',
                                  'type': 'boolean'},
                          'q_bins': {'description': 'Number of q-space bins',
                                     'minimum': 1,
                                     'semantic_type': 'integer',
                                     'type': 'integer'},
                          'q_max': {'description': 'Maximum q value',
                                    'minimum': 0,
                                    'semantic_type': 'float',
                                    'type': 'float'},
                          'r_max': {'description': 'Maximum real-space distance',
                                    'minimum': 0,
                                    'semantic_type': 'float',
                                    'type': 'float',
                                    'unit': 'nm'},
                          'selection': {'description': 'Atom selection for structure factor',
                                        'semantic_type': 'selection',
                                        'type': 'string'}},
               'name': 'structure_factor',
               'optional_fields': ['pbc', 'length_scale'],
               'outputs': [{'description': 'Structure factor vs q',
                            'fields': ['q_inv_nm', 'structure_factor'],
                            'format': 'npz',
                            'kind': 'histogram'}],
               'required_fields': ['selection', 'bins', 'r_max', 'q_bins', 'q_max'],
               'tags': ['structural']},
              {'aliases': ['surface-area', 'sas'],
               'description': 'Solvent accessible surface area',
               'examples': [{'mask': 'protein', 'name': 'surf'}],
               'fields': {'algorithm': {'description': 'Surface area algorithm',
                                        'semantic_type': 'string',
                                        'type': 'string'},
                          'mask': {'description': 'Atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'probe_radius': {'description': 'Probe radius',
                                           'minimum': 0,
                                           'semantic_type': 'float',
                                           'type': 'float',
                                           'unit': 'nm'}},
               'name': 'surf',
               'optional_fields': ['mask', 'algorithm', 'probe_radius', 'n_sphere_points', 'radii'],
               'outputs': [{'description': 'Surface area vs time',
                            'fields': ['time_ps', 'surface_area_nm2'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': [],
               'tags': ['structural', 'surface']},
              {'aliases': ['torsional-diffusion'],
               'description': 'Torsional diffusion coefficient',
               'examples': [{'mask': 'dihedral selection', 'name': 'tordiff'}],
               'fields': {'mask': {'description': 'Atom mask defining torsion',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'tstep': {'description': 'Time step in picoseconds',
                                    'semantic_type': 'float',
                                    'type': 'float'}},
               'name': 'tordiff',
               'optional_fields': ['tstep'],
               'outputs': [{'description': 'Torsional diffusion coefficient',
                            'fields': ['torsional_diffusion'],
                            'format': 'npz',
                            'kind': 'artifact'}],
               'required_fields': ['mask'],
               'tags': ['dynamic', 'diffusion']},
              {'aliases': ['volumetric-map', 'density-map'],
               'description': 'Volumetric density map',
               'examples': [{'grid_spacing': 0.1,
                             'mask': 'resname SOL and name OW',
                             'name': 'volmap'}],
               'fields': {'center': {'description': 'Grid center (x, y, z)',
                                     'semantic_type': 'vector',
                                     'type': 'array'},
                          'grid_spacing': {'description': 'Grid spacing',
                                           'minimum': 0,
                                           'semantic_type': 'float',
                                           'type': 'float',
                                           'unit': 'nm'},
                          'mask': {'description': 'Atom mask',
                                   'semantic_type': 'mask',
                                   'type': 'string'},
                          'size': {'description': 'Grid dimensions (nx, ny, nz)',
                                   'semantic_type': 'vector',
                                   'type': 'array'}},
               'name': 'volmap',
               'optional_fields': ['mask',
                                   'grid_spacing',
                                   'size',
                                   'center',
                                   'buffer',
                                   'centermask',
                                   'radscale',
                                   'peakcut',
                                   'dtype'],
               'outputs': [{'description': '3D volumetric density',
                            'fields': ['density'],
                            'format': 'dx',
                            'kind': 'grid'}],
               'required_fields': [],
               'tags': ['spatial', 'grid', 'solvent']},
              {'aliases': ['water-count'],
               'description': 'Water molecule count in spatial regions',
               'examples': [{'box_unit': [0.5, 0.5, 0.5],
                             'center_selection': 'resname LIG',
                             'name': 'water_count',
                             'region_size': [0.5, 0.5, 0.5],
                             'water_selection': 'resname SOL'}],
               'fields': {'box_unit': {'description': 'Box dimensions (x, y, z)',
                                       'semantic_type': 'vector',
                                       'type': 'array'},
                          'center_selection': {'description': 'Center point selection',
                                               'semantic_type': 'selection',
                                               'type': 'string'},
                          'region_size': {'description': 'Region dimensions (x, y, z)',
                                          'semantic_type': 'vector',
                                          'type': 'array'},
                          'shift': {'description': 'Origin shift (x, y, z)',
                                    'semantic_type': 'vector',
                                    'type': 'array'},
                          'water_selection': {'description': 'Water molecule selection',
                                              'semantic_type': 'selection',
                                              'type': 'string'}},
               'name': 'water_count',
               'optional_fields': ['shift', 'length_scale'],
               'outputs': [{'description': 'Water counts per region',
                            'fields': ['counts'],
                            'format': 'npz',
                            'kind': 'table'}],
               'required_fields': ['water_selection',
                                   'center_selection',
                                   'box_unit',
                                   'region_size'],
               'tags': ['solvent', 'spatial']},
              {'aliases': ['water-shell', 'solvation-shell'],
               'description': 'Water shell analysis around solute',
               'examples': [{'lower': 0.3,
                             'name': 'watershell',
                             'solute_mask': 'protein',
                             'upper': 0.5}],
               'fields': {'lower': {'description': 'Lower distance cutoff',
                                    'minimum': 0,
                                    'semantic_type': 'float',
                                    'type': 'float',
                                    'unit': 'nm'},
                          'solute_mask': {'description': 'Solute atom mask',
                                          'semantic_type': 'mask',
                                          'type': 'string'},
                          'solvent_mask': {'description': 'Solvent atom mask',
                                           'semantic_type': 'mask',
                                           'type': 'string'},
                          'upper': {'description': 'Upper distance cutoff',
                                    'minimum': 0,
                                    'semantic_type': 'float',
                                    'type': 'float',
                                    'unit': 'nm'}},
               'name': 'watershell',
               'optional_fields': ['solvent_mask', 'lower', 'upper', 'image'],
               'outputs': [{'description': 'Water count in shell vs time',
                            'fields': ['time_ps', 'water_count'],
                            'format': 'npz',
                            'kind': 'timeseries'}],
               'required_fields': ['solute_mask'],
               'tags': ['solvent', 'solvation']}],
 'analysis_shared_fields': ['chunk_frames', 'device', 'out'],
 'cli_to_analysis': {'bond-angle-distribution': 'bond_angle_distribution',
                     'bond-length-distribution': 'bond_length_distribution',
                     'bond_angle_distribution': 'bond_angle_distribution',
                     'bond_length_distribution': 'bond_length_distribution',
                     'bondi-ffv': 'bondi_ffv',
                     'bondi_ffv': 'bondi_ffv',
                     'chain-rg': 'chain_rg',
                     'chain_rg': 'chain_rg',
                     'conductivity': 'conductivity',
                     'contour-length': 'contour_length',
                     'contour_length': 'contour_length',
                     'density': 'density',
                     'dielectric': 'dielectric',
                     'diffusion': 'diffusion',
                     'dipole-alignment': 'dipole_alignment',
                     'dipole_alignment': 'dipole_alignment',
                     'docking': 'docking',
                     'dssp': 'dssp',
                     'helix': 'helix',
                     'end-to-end': 'end_to_end',
                     'end_to_end': 'end_to_end',
                     'equipartition': 'equipartition',
                     'ffv': 'bondi_ffv',
                     'fractional-free-volume': 'bondi_ffv',
                     'free-volume': 'free_volume',
                     'free-volume-grid': 'free_volume',
                     'free_volume': 'free_volume',
                     'gist': 'gist',
                     'hbond': 'hbond',
                     'ion-pair-correlation': 'ion_pair_correlation',
                     'ion_pair_correlation': 'ion_pair_correlation',
                     'jcoupling': 'jcoupling',
                     'molsurf': 'molsurf',
                     'msd': 'msd',
                     'native-contacts': 'native_contacts',
                     'native_contacts': 'native_contacts',
                     'nmr': 'nmr',
                     'pca': 'pca',
                     'persistence-length': 'persistence_length',
                     'persistence_length': 'persistence_length',
                     'projection': 'projection',
                     'rdf': 'rdf',
                     'rg': 'rg',
                     'rmsd': 'rmsd',
                     'rmsf': 'rmsf',
                     'rotacf': 'rotacf',
                     'structure-factor': 'structure_factor',
                     'structure_factor': 'structure_factor',
                     'surf': 'surf',
                     'tordiff': 'tordiff',
                     'volmap': 'volmap',
                     'voxel-free-volume': 'free_volume',
                     'water-count': 'water_count',
                     'water_count': 'water_count',
                     'watershell': 'watershell'},
 'schema_version': 'warp-md.agent.v1'}
