from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AnalysisEntry:
    cli_name: str
    plan_name: str
    setup_fn: str | None
    spec_fn: str | None
    build_fn: str
    legacy_cli_aliases: tuple[str, ...] = ()


ANALYSIS_REGISTRY: tuple[AnalysisEntry, ...] = (
    AnalysisEntry("rg", "rg", "setup_rg_args", "_spec_rg", "_build_rg"),
    AnalysisEntry("rmsd", "rmsd", "setup_rmsd_args", "_spec_rmsd", "_build_rmsd"),
    AnalysisEntry("msd", "msd", "setup_msd_args", "_spec_msd", "_build_msd"),
    AnalysisEntry("rotacf", "rotacf", "setup_rotacf_args", "_spec_rotacf", "_build_rotacf"),
    AnalysisEntry(
        "conductivity",
        "conductivity",
        "setup_conductivity_args",
        "_spec_conductivity",
        "_build_conductivity",
    ),
    AnalysisEntry(
        "dielectric",
        "dielectric",
        "setup_dielectric_args",
        "_spec_dielectric",
        "_build_dielectric",
    ),
    AnalysisEntry(
        "dipole-alignment",
        "dipole_alignment",
        "setup_dipole_alignment_args",
        "_spec_dipole_alignment",
        "_build_dipole_alignment",
    ),
    AnalysisEntry(
        "ion-pair-correlation",
        "ion_pair_correlation",
        "setup_ion_pair_args",
        "_spec_ion_pair",
        "_build_ion_pair",
    ),
    AnalysisEntry(
        "structure-factor",
        "structure_factor",
        "setup_structure_factor_args",
        "_spec_structure_factor",
        "_build_structure_factor",
    ),
    AnalysisEntry(
        "water-count",
        "water_count",
        "setup_water_count_args",
        "_spec_water_count",
        "_build_water_count",
    ),
    AnalysisEntry(
        "free-volume",
        "free_volume",
        "setup_free_volume_args",
        "_spec_free_volume",
        "_build_free_volume",
    ),
    AnalysisEntry(
        "bondi-ffv",
        "bondi_ffv",
        "setup_bondi_ffv_args",
        "_spec_bondi_ffv",
        "_build_bondi_ffv",
        legacy_cli_aliases=("ffv",),
    ),
    AnalysisEntry(
        "equipartition",
        "equipartition",
        "setup_equipartition_args",
        "_spec_equipartition",
        "_build_equipartition",
    ),
    AnalysisEntry("hbond", "hbond", "setup_hbond_args", "_spec_hbond", "_build_hbond"),
    AnalysisEntry("rdf", "rdf", "setup_rdf_args", "_spec_rdf", "_build_rdf"),
    AnalysisEntry(
        "end-to-end",
        "end_to_end",
        "setup_end_to_end_args",
        "_spec_end_to_end",
        "_build_end_to_end",
    ),
    AnalysisEntry(
        "contour-length",
        "contour_length",
        "setup_contour_length_args",
        "_spec_contour_length",
        "_build_contour_length",
    ),
    AnalysisEntry(
        "chain-rg",
        "chain_rg",
        "setup_chain_rg_args",
        "_spec_chain_rg",
        "_build_chain_rg",
    ),
    AnalysisEntry(
        "bond-length-distribution",
        "bond_length_distribution",
        "setup_bond_length_args",
        "_spec_bond_length",
        "_build_bond_length",
    ),
    AnalysisEntry(
        "bond-angle-distribution",
        "bond_angle_distribution",
        "setup_bond_angle_args",
        "_spec_bond_angle",
        "_build_bond_angle",
    ),
    AnalysisEntry(
        "persistence-length",
        "persistence_length",
        "setup_persistence_args",
        "_spec_persistence",
        "_build_persistence",
    ),
    AnalysisEntry("docking", "docking", None, None, "_build_docking"),
    AnalysisEntry("dssp", "dssp", None, None, "_build_dssp"),
    AnalysisEntry("diffusion", "diffusion", None, None, "_build_diffusion"),
    AnalysisEntry("pca", "pca", None, None, "_build_pca"),
    AnalysisEntry("rmsf", "rmsf", None, None, "_build_rmsf"),
    AnalysisEntry("density", "density", None, None, "_build_density"),
    AnalysisEntry("native-contacts", "native_contacts", None, None, "_build_native_contacts"),
    AnalysisEntry("volmap", "volmap", None, None, "_build_volmap"),
    AnalysisEntry("surf", "surf", None, None, "_build_surf"),
    AnalysisEntry("molsurf", "molsurf", None, None, "_build_molsurf"),
    AnalysisEntry("watershell", "watershell", None, None, "_build_watershell"),
    AnalysisEntry("tordiff", "tordiff", None, None, "_build_tordiff"),
    AnalysisEntry("projection", "projection", None, None, "_build_projection"),
    AnalysisEntry("nmr", "nmr", None, None, "_build_nmr"),
    AnalysisEntry("jcoupling", "jcoupling", None, None, "_build_jcoupling"),
    AnalysisEntry("gist", "gist", None, None, "_build_gist"),
    AnalysisEntry(
        "lipid-leaflets",
        "lipid_leaflets",
        "setup_lipid_leaflets_args",
        "_spec_lipid_leaflets",
        "_build_lipid_leaflets",
    ),
    AnalysisEntry(
        "lipid-curved-leaflets",
        "lipid_curved_leaflets",
        "setup_lipid_curved_leaflets_args",
        "_spec_lipid_curved_leaflets",
        "_build_lipid_curved_leaflets",
    ),
    AnalysisEntry(
        "lipid-z-positions",
        "lipid_z_positions",
        "setup_lipid_z_positions_args",
        "_spec_lipid_z_positions",
        "_build_lipid_z_positions",
    ),
    AnalysisEntry(
        "lipid-z-thickness",
        "lipid_z_thickness",
        "setup_lipid_z_thickness_args",
        "_spec_lipid_z_thickness",
        "_build_lipid_z_thickness",
    ),
    AnalysisEntry(
        "lipid-z-angles",
        "lipid_z_angles",
        "setup_lipid_z_angles_args",
        "_spec_lipid_z_angles",
        "_build_lipid_z_angles",
    ),
    AnalysisEntry(
        "lipid-area",
        "lipid_area",
        "setup_lipid_area_args",
        "_spec_lipid_area",
        "_build_lipid_area",
    ),
    AnalysisEntry(
        "lipid-flip-flop",
        "lipid_flip_flop",
        "setup_lipid_flip_flop_args",
        "_spec_lipid_flip_flop",
        "_build_lipid_flip_flop",
    ),
    AnalysisEntry(
        "lipid-neighbours",
        "lipid_neighbours",
        "setup_lipid_neighbours_args",
        "_spec_lipid_neighbours",
        "_build_lipid_neighbours",
    ),
    AnalysisEntry(
        "lipid-neighbour-matrix",
        "lipid_neighbour_matrix",
        "setup_lipid_neighbour_matrix_args",
        "_spec_lipid_neighbour_matrix",
        "_build_lipid_neighbour_matrix",
    ),
    AnalysisEntry(
        "lipid-largest-cluster",
        "lipid_largest_cluster",
        "setup_lipid_largest_cluster_args",
        "_spec_lipid_largest_cluster",
        "_build_lipid_largest_cluster",
    ),
    AnalysisEntry(
        "lipid-membrane-thickness",
        "lipid_membrane_thickness",
        "setup_lipid_membrane_thickness_args",
        "_spec_lipid_membrane_thickness",
        "_build_lipid_membrane_thickness",
    ),
    AnalysisEntry(
        "lipid-registration",
        "lipid_registration",
        "setup_lipid_registration_args",
        "_spec_lipid_registration",
        "_build_lipid_registration",
    ),
    AnalysisEntry(
        "lipid-msd",
        "lipid_msd",
        "setup_lipid_msd_args",
        "_spec_lipid_msd",
        "_build_lipid_msd",
    ),
    AnalysisEntry(
        "lipid-scc",
        "lipid_scc",
        "setup_lipid_scc_args",
        "_spec_lipid_scc",
        "_build_lipid_scc",
    ),
)
